// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_server.proto

package ca.wise.rpc.proto;

public interface FileChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.FileChunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the job that the file is for.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the job that the file is for.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The bytes from the file.
   * </pre>
   *
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   * The file format to save the data in.
   * </pre>
   *
   * <code>.rpc.FileChunk.OutputType type = 3;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   * The file format to save the data in.
   * </pre>
   *
   * <code>.rpc.FileChunk.OutputType type = 3;</code>
   */
  ca.wise.rpc.proto.FileChunk.OutputType getType();
}
