//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.08 at 07:03:29 PM CDT 
//


package ca.wise.fgm.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Accel complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Accel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Closed"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="C2"/&gt;
 *                         &lt;enumeration value="C3"/&gt;
 *                         &lt;enumeration value="C4"/&gt;
 *                         &lt;enumeration value="C5"/&gt;
 *                         &lt;enumeration value="C6"/&gt;
 *                         &lt;enumeration value="C7"/&gt;
 *                         &lt;enumeration value="D1"/&gt;
 *                         &lt;enumeration value="M1"/&gt;
 *                         &lt;enumeration value="M2"/&gt;
 *                         &lt;enumeration value="M3"/&gt;
 *                         &lt;enumeration value="M4"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Eq72_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq72_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq72_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq72_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Open"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="C1"/&gt;
 *                         &lt;enumeration value="O1a"/&gt;
 *                         &lt;enumeration value="O1b"/&gt;
 *                         &lt;enumeration value="O1ab"/&gt;
 *                         &lt;enumeration value="S1"/&gt;
 *                         &lt;enumeration value="S2"/&gt;
 *                         &lt;enumeration value="S3"/&gt;
 *                         &lt;enumeration value="NonFuel"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Accel", namespace = "FBP_Schema", propOrder = {
    "closed",
    "open"
})
public class Accel {

    @XmlElement(name = "Closed", namespace = "FBP_Schema")
    protected Accel.Closed closed;
    @XmlElement(name = "Open", namespace = "FBP_Schema")
    protected Accel.Open open;

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link Accel.Closed }
     *     
     */
    public Accel.Closed getClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accel.Closed }
     *     
     */
    public void setClosed(Accel.Closed value) {
        this.closed = value;
    }

    /**
     * Gets the value of the open property.
     * 
     * @return
     *     possible object is
     *     {@link Accel.Open }
     *     
     */
    public Accel.Open getOpen() {
        return open;
    }

    /**
     * Sets the value of the open property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accel.Open }
     *     
     */
    public void setOpen(Accel.Open value) {
        this.open = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="C2"/&gt;
     *               &lt;enumeration value="C3"/&gt;
     *               &lt;enumeration value="C4"/&gt;
     *               &lt;enumeration value="C5"/&gt;
     *               &lt;enumeration value="C6"/&gt;
     *               &lt;enumeration value="C7"/&gt;
     *               &lt;enumeration value="D1"/&gt;
     *               &lt;enumeration value="M1"/&gt;
     *               &lt;enumeration value="M2"/&gt;
     *               &lt;enumeration value="M3"/&gt;
     *               &lt;enumeration value="M4"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Eq72_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq72_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq72_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq72_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class Closed {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected Accel.Closed.Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link Accel.Closed.Custom }
         *     
         */
        public Accel.Closed.Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accel.Closed.Custom }
         *     
         */
        public void setCustom(Accel.Closed.Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Eq72_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq72_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq72_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq72_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Eq72_P1", required = true)
            protected String eq72P1;
            @XmlAttribute(name = "Eq72_P2", required = true)
            protected String eq72P2;
            @XmlAttribute(name = "Eq72_P3", required = true)
            protected String eq72P3;
            @XmlAttribute(name = "Eq72_P4", required = true)
            protected String eq72P4;

            /**
             * Gets the value of the eq72P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq72P1() {
                return eq72P1;
            }

            /**
             * Sets the value of the eq72P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq72P1(String value) {
                this.eq72P1 = value;
            }

            /**
             * Gets the value of the eq72P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq72P2() {
                return eq72P2;
            }

            /**
             * Sets the value of the eq72P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq72P2(String value) {
                this.eq72P2 = value;
            }

            /**
             * Gets the value of the eq72P3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq72P3() {
                return eq72P3;
            }

            /**
             * Sets the value of the eq72P3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq72P3(String value) {
                this.eq72P3 = value;
            }

            /**
             * Gets the value of the eq72P4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq72P4() {
                return eq72P4;
            }

            /**
             * Sets the value of the eq72P4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq72P4(String value) {
                this.eq72P4 = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="C1"/&gt;
     *               &lt;enumeration value="O1a"/&gt;
     *               &lt;enumeration value="O1b"/&gt;
     *               &lt;enumeration value="O1ab"/&gt;
     *               &lt;enumeration value="S1"/&gt;
     *               &lt;enumeration value="S2"/&gt;
     *               &lt;enumeration value="S3"/&gt;
     *               &lt;enumeration value="NonFuel"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class Open {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected Accel.Open.Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link Accel.Open.Custom }
         *     
         */
        public Accel.Open.Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accel.Open.Custom }
         *     
         */
        public void setCustom(Accel.Open.Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Value", required = true)
            protected String value;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
