//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.10 at 10:49:01 AM CST 
//


package ca.wise.fgm.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coordinateType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coordinateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="lat" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *       &lt;attribute name="lon" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *       &lt;attribute name="utmX" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *       &lt;attribute name="utmY" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *       &lt;attribute name="gridX" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *       &lt;attribute name="gridY" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coordinateType")
public class CoordinateType {

    @XmlAttribute(name = "lat", required = true)
    protected String lat;
    @XmlAttribute(name = "lon", required = true)
    protected String lon;
    @XmlAttribute(name = "utmX")
    protected String utmX;
    @XmlAttribute(name = "utmY")
    protected String utmY;
    @XmlAttribute(name = "gridX")
    protected String gridX;
    @XmlAttribute(name = "gridY")
    protected String gridY;

    /**
     * Gets the value of the lat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLat(String value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLon(String value) {
        this.lon = value;
    }

    /**
     * Gets the value of the utmX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtmX() {
        return utmX;
    }

    /**
     * Sets the value of the utmX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtmX(String value) {
        this.utmX = value;
    }

    /**
     * Gets the value of the utmY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtmY() {
        return utmY;
    }

    /**
     * Sets the value of the utmY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtmY(String value) {
        this.utmY = value;
    }

    /**
     * Gets the value of the gridX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridX() {
        return gridX;
    }

    /**
     * Sets the value of the gridX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridX(String value) {
        this.gridX = value;
    }

    /**
     * Gets the value of the gridY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridY() {
        return gridY;
    }

    /**
     * Sets the value of the gridY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridY(String value) {
        this.gridY = value;
    }

}
