//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.28 at 08:13:41 PM CST 
//


package ca.wise.fgm.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.cwfgm.psaas.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.cwfgm.psaas.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Defaults }
     * 
     */
    public Defaults createDefaults() {
        return new Defaults();
    }

    /**
     * Create an instance of {@link FuelMap }
     * 
     */
    public FuelMap createFuelMap() {
        return new FuelMap();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link Outputs }
     * 
     */
    public Outputs createOutputs() {
        return new Outputs();
    }

    /**
     * Create an instance of {@link Outputs.GridFiles }
     * 
     */
    public Outputs.GridFiles createOutputsGridFiles() {
        return new Outputs.GridFiles();
    }

    /**
     * Create an instance of {@link Outputs.VectorFiles }
     * 
     */
    public Outputs.VectorFiles createOutputsVectorFiles() {
        return new Outputs.VectorFiles();
    }

    /**
     * Create an instance of {@link Outputs.VectorFiles.VectorFile }
     * 
     */
    public Outputs.VectorFiles.VectorFile createOutputsVectorFilesVectorFile() {
        return new Outputs.VectorFiles.VectorFile();
    }

    /**
     * Create an instance of {@link Outputs.SummaryFiles }
     * 
     */
    public Outputs.SummaryFiles createOutputsSummaryFiles() {
        return new Outputs.SummaryFiles();
    }

    /**
     * Create an instance of {@link FlameLength }
     * 
     */
    public FlameLength createFlameLength() {
        return new FlameLength();
    }

    /**
     * Create an instance of {@link FlameLength.Other }
     * 
     */
    public FlameLength.Other createFlameLengthOther() {
        return new FlameLength.Other();
    }

    /**
     * Create an instance of {@link FlameLength.Tree }
     * 
     */
    public FlameLength.Tree createFlameLengthTree() {
        return new FlameLength.Tree();
    }

    /**
     * Create an instance of {@link FlameLength.Alexander82Tree }
     * 
     */
    public FlameLength.Alexander82Tree createFlameLengthAlexander82Tree() {
        return new FlameLength.Alexander82Tree();
    }

    /**
     * Create an instance of {@link FlameLength.Alexander82 }
     * 
     */
    public FlameLength.Alexander82 createFlameLengthAlexander82() {
        return new FlameLength.Alexander82();
    }

    /**
     * Create an instance of {@link SFC }
     * 
     */
    public SFC createSFC() {
        return new SFC();
    }

    /**
     * Create an instance of {@link SFC.S1 }
     * 
     */
    public SFC.S1 createSFCS1() {
        return new SFC.S1();
    }

    /**
     * Create an instance of {@link SFC.O1 }
     * 
     */
    public SFC.O1 createSFCO1() {
        return new SFC.O1();
    }

    /**
     * Create an instance of {@link SFC.D2 }
     * 
     */
    public SFC.D2 createSFCD2() {
        return new SFC.D2();
    }

    /**
     * Create an instance of {@link SFC.C7 }
     * 
     */
    public SFC.C7 createSFCC7() {
        return new SFC.C7();
    }

    /**
     * Create an instance of {@link SFC.C2 }
     * 
     */
    public SFC.C2 createSFCC2() {
        return new SFC.C2();
    }

    /**
     * Create an instance of {@link SFC.C1 }
     * 
     */
    public SFC.C1 createSFCC1() {
        return new SFC.C1();
    }

    /**
     * Create an instance of {@link TFC }
     * 
     */
    public TFC createTFC() {
        return new TFC();
    }

    /**
     * Create an instance of {@link RSI }
     * 
     */
    public RSI createRSI() {
        return new RSI();
    }

    /**
     * Create an instance of {@link RSI.Constant }
     * 
     */
    public RSI.Constant createRSIConstant() {
        return new RSI.Constant();
    }

    /**
     * Create an instance of {@link RSI.O1 }
     * 
     */
    public RSI.O1 createRSIO1() {
        return new RSI.O1();
    }

    /**
     * Create an instance of {@link RSI.M4 }
     * 
     */
    public RSI.M4 createRSIM4() {
        return new RSI.M4();
    }

    /**
     * Create an instance of {@link RSI.M3 }
     * 
     */
    public RSI.M3 createRSIM3() {
        return new RSI.M3();
    }

    /**
     * Create an instance of {@link RSI.M1 }
     * 
     */
    public RSI.M1 createRSIM1() {
        return new RSI.M1();
    }

    /**
     * Create an instance of {@link RSI.D2 }
     * 
     */
    public RSI.D2 createRSID2() {
        return new RSI.D2();
    }

    /**
     * Create an instance of {@link RSI.C6 }
     * 
     */
    public RSI.C6 createRSIC6() {
        return new RSI.C6();
    }

    /**
     * Create an instance of {@link ISF }
     * 
     */
    public ISF createISF() {
        return new ISF();
    }

    /**
     * Create an instance of {@link ISF.O1 }
     * 
     */
    public ISF.O1 createISFO1() {
        return new ISF.O1();
    }

    /**
     * Create an instance of {@link ISF.M3 }
     * 
     */
    public ISF.M3 createISFM3() {
        return new ISF.M3();
    }

    /**
     * Create an instance of {@link CFB }
     * 
     */
    public CFB createCFB() {
        return new CFB();
    }

    /**
     * Create an instance of {@link CFB.C1 }
     * 
     */
    public CFB.C1 createCFBC1() {
        return new CFB.C1();
    }

    /**
     * Create an instance of {@link Accel }
     * 
     */
    public Accel createAccel() {
        return new Accel();
    }

    /**
     * Create an instance of {@link Accel.Open }
     * 
     */
    public Accel.Open createAccelOpen() {
        return new Accel.Open();
    }

    /**
     * Create an instance of {@link Accel.Closed }
     * 
     */
    public Accel.Closed createAccelClosed() {
        return new Accel.Closed();
    }

    /**
     * Create an instance of {@link LB }
     * 
     */
    public LB createLB() {
        return new LB();
    }

    /**
     * Create an instance of {@link LB.O1 }
     * 
     */
    public LB.O1 createLBO1() {
        return new LB.O1();
    }

    /**
     * Create an instance of {@link LB.C1 }
     * 
     */
    public LB.C1 createLBC1() {
        return new LB.C1();
    }

    /**
     * Create an instance of {@link FMC }
     * 
     */
    public FMC createFMC() {
        return new FMC();
    }

    /**
     * Create an instance of {@link FBPFuelType }
     * 
     */
    public FBPFuelType createFBPFuelType() {
        return new FBPFuelType();
    }

    /**
     * Create an instance of {@link FBPFuelType.IsModified }
     * 
     */
    public FBPFuelType.IsModified createFBPFuelTypeIsModified() {
        return new FBPFuelType.IsModified();
    }

    /**
     * Create an instance of {@link DailyCondition }
     * 
     */
    public DailyCondition createDailyCondition() {
        return new DailyCondition();
    }

    /**
     * Create an instance of {@link DailyCondition.HourWeather }
     * 
     */
    public DailyCondition.HourWeather createDailyConditionHourWeather() {
        return new DailyCondition.HourWeather();
    }

    /**
     * Create an instance of {@link WeatherStation }
     * 
     */
    public WeatherStation createWeatherStation() {
        return new WeatherStation();
    }

    /**
     * Create an instance of {@link WeatherStream }
     * 
     */
    public WeatherStream createWeatherStream() {
        return new WeatherStream();
    }

    /**
     * Create an instance of {@link WeatherStream.DiurnalParameters }
     * 
     */
    public WeatherStream.DiurnalParameters createWeatherStreamDiurnalParameters() {
        return new WeatherStream.DiurnalParameters();
    }

    /**
     * Create an instance of {@link WeatherGridData }
     * 
     */
    public WeatherGridData createWeatherGridData() {
        return new WeatherGridData();
    }

    /**
     * Create an instance of {@link WeatherGridData.Sectors }
     * 
     */
    public WeatherGridData.Sectors createWeatherGridDataSectors() {
        return new WeatherGridData.Sectors();
    }

    /**
     * Create an instance of {@link WeatherGridData.Sectors.SectorList }
     * 
     */
    public WeatherGridData.Sectors.SectorList createWeatherGridDataSectorsSectorList() {
        return new WeatherGridData.Sectors.SectorList();
    }

    /**
     * Create an instance of {@link WeatherGridData.Sectors.SectorList.Sector }
     * 
     */
    public WeatherGridData.Sectors.SectorList.Sector createWeatherGridDataSectorsSectorListSector() {
        return new WeatherGridData.Sectors.SectorList.Sector();
    }

    /**
     * Create an instance of {@link WeatherGridData.Sectors.SectorList.Sector.Direction }
     * 
     */
    public WeatherGridData.Sectors.SectorList.Sector.Direction createWeatherGridDataSectorsSectorListSectorDirection() {
        return new WeatherGridData.Sectors.SectorList.Sector.Direction();
    }

    /**
     * Create an instance of {@link WcsData }
     * 
     */
    public WcsData createWcsData() {
        return new WcsData();
    }

    /**
     * Create an instance of {@link WfsData }
     * 
     */
    public WfsData createWfsData() {
        return new WfsData();
    }

    /**
     * Create an instance of {@link WfsData.VectorData }
     * 
     */
    public WfsData.VectorData createWfsDataVectorData() {
        return new WfsData.VectorData();
    }

    /**
     * Create an instance of {@link Data.Job }
     * 
     */
    public Data.Job createDataJob() {
        return new Data.Job();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs }
     * 
     */
    public Data.Job.Inputs createDataJobInputs() {
        return new Data.Job.Inputs();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios }
     * 
     */
    public Data.Job.Inputs.Scenarios createDataJobInputsScenarios() {
        return new Data.Job.Inputs.Scenarios();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy createDataJobInputsScenariosScenarioCopy() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.StreamInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.StreamInfo createDataJobInputsScenariosScenarioCopyStreamInfo() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.StreamInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.LayerInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.LayerInfo createDataJobInputsScenariosScenarioCopyLayerInfo() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.LayerInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario createDataJobInputsScenariosScenario() {
        return new Data.Job.Inputs.Scenarios.Scenario();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.StreamInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.StreamInfo createDataJobInputsScenariosScenarioStreamInfo() {
        return new Data.Job.Inputs.Scenarios.Scenario.StreamInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.LayerInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.LayerInfo createDataJobInputsScenariosScenarioLayerInfo() {
        return new Data.Job.Inputs.Scenarios.Scenario.LayerInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Ignitions }
     * 
     */
    public Data.Job.Inputs.Ignitions createDataJobInputsIgnitions() {
        return new Data.Job.Inputs.Ignitions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Ignitions.Ignition }
     * 
     */
    public Data.Job.Inputs.Ignitions.Ignition createDataJobInputsIgnitionsIgnition() {
        return new Data.Job.Inputs.Ignitions.Ignition();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files }
     * 
     */
    public Data.Job.Inputs.Files createDataJobInputsFiles() {
        return new Data.Job.Inputs.Files();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles createDataJobInputsFilesWeatherPatchFiles() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile createDataJobInputsFilesWeatherPatchFilesPatchFile() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Geographic }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Geographic createDataJobInputsFilesWeatherPatchFilesPatchFileGeographic() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Geographic();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.GridFiles }
     * 
     */
    public Data.Job.Inputs.Files.GridFiles createDataJobInputsFilesGridFiles() {
        return new Data.Job.Inputs.Files.GridFiles();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.GridFiles.GridFile }
     * 
     */
    public Data.Job.Inputs.Files.GridFiles.GridFile createDataJobInputsFilesGridFilesGridFile() {
        return new Data.Job.Inputs.Files.GridFiles.GridFile();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelPatchFiles }
     * 
     */
    public Data.Job.Inputs.Files.FuelPatchFiles createDataJobInputsFilesFuelPatchFiles() {
        return new Data.Job.Inputs.Files.FuelPatchFiles();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile }
     * 
     */
    public Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile createDataJobInputsFilesFuelPatchFilesFuelPatchFile() {
        return new Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic }
     * 
     */
    public Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic createDataJobInputsFilesFuelPatchFilesFuelPatchFileGeographic() {
        return new Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelbreakFiles }
     * 
     */
    public Data.Job.Inputs.Files.FuelbreakFiles createDataJobInputsFilesFuelbreakFiles() {
        return new Data.Job.Inputs.Files.FuelbreakFiles();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.LutFile }
     * 
     */
    public Data.Job.Inputs.Files.LutFile createDataJobInputsFilesLutFile() {
        return new Data.Job.Inputs.Files.LutFile();
    }

    /**
     * Create an instance of {@link Data.Params }
     * 
     */
    public Data.Params createDataParams() {
        return new Data.Params();
    }

    /**
     * Create an instance of {@link Defaults.Job }
     * 
     */
    public Defaults.Job createDefaultsJob() {
        return new Defaults.Job();
    }

    /**
     * Create an instance of {@link Defaults.Job.VectorFile }
     * 
     */
    public Defaults.Job.VectorFile createDefaultsJobVectorFile() {
        return new Defaults.Job.VectorFile();
    }

    /**
     * Create an instance of {@link Defaults.Log }
     * 
     */
    public Defaults.Log createDefaultsLog() {
        return new Defaults.Log();
    }

    /**
     * Create an instance of {@link Defaults.Signals }
     * 
     */
    public Defaults.Signals createDefaultsSignals() {
        return new Defaults.Signals();
    }

    /**
     * Create an instance of {@link Defaults.Hardware }
     * 
     */
    public Defaults.Hardware createDefaultsHardware() {
        return new Defaults.Hardware();
    }

    /**
     * Create an instance of {@link Defaults.Mqtt }
     * 
     */
    public Defaults.Mqtt createDefaultsMqtt() {
        return new Defaults.Mqtt();
    }

    /**
     * Create an instance of {@link FuelMap.FuelType }
     * 
     */
    public FuelMap.FuelType createFuelMapFuelType() {
        return new FuelMap.FuelType();
    }

    /**
     * Create an instance of {@link ViewCollection }
     * 
     */
    public ViewCollection createViewCollection() {
        return new ViewCollection();
    }

    /**
     * Create an instance of {@link WfsExternalData }
     * 
     */
    public WfsExternalData createWfsExternalData() {
        return new WfsExternalData();
    }

    /**
     * Create an instance of {@link WcsExternalData }
     * 
     */
    public WcsExternalData createWcsExternalData() {
        return new WcsExternalData();
    }

    /**
     * Create an instance of {@link List.Status }
     * 
     */
    public List.Status createListStatus() {
        return new List.Status();
    }

    /**
     * Create an instance of {@link List.Message }
     * 
     */
    public List.Message createListMessage() {
        return new List.Message();
    }

    /**
     * Create an instance of {@link WindGridData }
     * 
     */
    public WindGridData createWindGridData() {
        return new WindGridData();
    }

    /**
     * Create an instance of {@link ViewState }
     * 
     */
    public ViewState createViewState() {
        return new ViewState();
    }

    /**
     * Create an instance of {@link WindowPlacement }
     * 
     */
    public WindowPlacement createWindowPlacement() {
        return new WindowPlacement();
    }

    /**
     * Create an instance of {@link ca.wise.fgm.xml.Point }
     * 
     */
    public ca.wise.fgm.xml.Point createPoint() {
        return new ca.wise.fgm.xml.Point();
    }

    /**
     * Create an instance of {@link Rect }
     * 
     */
    public Rect createRect() {
        return new Rect();
    }

    /**
     * Create an instance of {@link BurnCondition }
     * 
     */
    public BurnCondition createBurnCondition() {
        return new BurnCondition();
    }

    /**
     * Create an instance of {@link TemporalStateCondition }
     * 
     */
    public TemporalStateCondition createTemporalStateCondition() {
        return new TemporalStateCondition();
    }

    /**
     * Create an instance of {@link PercentileEntry }
     * 
     */
    public PercentileEntry createPercentileEntry() {
        return new PercentileEntry();
    }

    /**
     * Create an instance of {@link CoordinateType }
     * 
     */
    public CoordinateType createCoordinateType() {
        return new CoordinateType();
    }

    /**
     * Create an instance of {@link MqttConfig }
     * 
     */
    public MqttConfig createMqttConfig() {
        return new MqttConfig();
    }

    /**
     * Create an instance of {@link WcsType }
     * 
     */
    public WcsType createWcsType() {
        return new WcsType();
    }

    /**
     * Create an instance of {@link WfsType }
     * 
     */
    public WfsType createWfsType() {
        return new WfsType();
    }

    /**
     * Create an instance of {@link Outputs.GridFiles.GridFile }
     * 
     */
    public Outputs.GridFiles.GridFile createOutputsGridFilesGridFile() {
        return new Outputs.GridFiles.GridFile();
    }

    /**
     * Create an instance of {@link Outputs.VectorFiles.VectorFile.Metadata }
     * 
     */
    public Outputs.VectorFiles.VectorFile.Metadata createOutputsVectorFilesVectorFileMetadata() {
        return new Outputs.VectorFiles.VectorFile.Metadata();
    }

    /**
     * Create an instance of {@link Outputs.VectorFiles.VectorFile.PerimTime }
     * 
     */
    public Outputs.VectorFiles.VectorFile.PerimTime createOutputsVectorFilesVectorFilePerimTime() {
        return new Outputs.VectorFiles.VectorFile.PerimTime();
    }

    /**
     * Create an instance of {@link Outputs.SummaryFiles.Summary }
     * 
     */
    public Outputs.SummaryFiles.Summary createOutputsSummaryFilesSummary() {
        return new Outputs.SummaryFiles.Summary();
    }

    /**
     * Create an instance of {@link FlameLength.Other.Custom }
     * 
     */
    public FlameLength.Other.Custom createFlameLengthOtherCustom() {
        return new FlameLength.Other.Custom();
    }

    /**
     * Create an instance of {@link FlameLength.Tree.Custom }
     * 
     */
    public FlameLength.Tree.Custom createFlameLengthTreeCustom() {
        return new FlameLength.Tree.Custom();
    }

    /**
     * Create an instance of {@link FlameLength.Alexander82Tree.Custom }
     * 
     */
    public FlameLength.Alexander82Tree.Custom createFlameLengthAlexander82TreeCustom() {
        return new FlameLength.Alexander82Tree.Custom();
    }

    /**
     * Create an instance of {@link FlameLength.Alexander82 .Custom }
     * 
     */
    public FlameLength.Alexander82 .Custom createFlameLengthAlexander82Custom() {
        return new FlameLength.Alexander82 .Custom();
    }

    /**
     * Create an instance of {@link DBH.None }
     * 
     */
    public DBH.None createDBHNone() {
        return new DBH.None();
    }

    /**
     * Create an instance of {@link DBH.Huang4 .Custom }
     * 
     */
    public DBH.Huang4 .Custom createDBHHuang4Custom() {
        return new DBH.Huang4 .Custom();
    }

    /**
     * Create an instance of {@link DBH.Huang3 .Custom }
     * 
     */
    public DBH.Huang3 .Custom createDBHHuang3Custom() {
        return new DBH.Huang3 .Custom();
    }

    /**
     * Create an instance of {@link DBH.Huang2 .Custom }
     * 
     */
    public DBH.Huang2 .Custom createDBHHuang2Custom() {
        return new DBH.Huang2 .Custom();
    }

    /**
     * Create an instance of {@link DBH.Huang1 .Custom }
     * 
     */
    public DBH.Huang1 .Custom createDBHHuang1Custom() {
        return new DBH.Huang1 .Custom();
    }

    /**
     * Create an instance of {@link SFC.M1 }
     * 
     */
    public SFC.M1 createSFCM1() {
        return new SFC.M1();
    }

    /**
     * Create an instance of {@link SFC.S1 .Custom }
     * 
     */
    public SFC.S1 .Custom createSFCS1Custom() {
        return new SFC.S1 .Custom();
    }

    /**
     * Create an instance of {@link SFC.O1 .Custom }
     * 
     */
    public SFC.O1 .Custom createSFCO1Custom() {
        return new SFC.O1 .Custom();
    }

    /**
     * Create an instance of {@link SFC.D2 .Custom }
     * 
     */
    public SFC.D2 .Custom createSFCD2Custom() {
        return new SFC.D2 .Custom();
    }

    /**
     * Create an instance of {@link SFC.C7 .Custom }
     * 
     */
    public SFC.C7 .Custom createSFCC7Custom() {
        return new SFC.C7 .Custom();
    }

    /**
     * Create an instance of {@link SFC.C2 .Custom }
     * 
     */
    public SFC.C2 .Custom createSFCC2Custom() {
        return new SFC.C2 .Custom();
    }

    /**
     * Create an instance of {@link SFC.C1 .Custom }
     * 
     */
    public SFC.C1 .Custom createSFCC1Custom() {
        return new SFC.C1 .Custom();
    }

    /**
     * Create an instance of {@link TFC.C1 }
     * 
     */
    public TFC.C1 createTFCC1() {
        return new TFC.C1();
    }

    /**
     * Create an instance of {@link TFC.D2 }
     * 
     */
    public TFC.D2 createTFCD2() {
        return new TFC.D2();
    }

    /**
     * Create an instance of {@link TFC.M1 }
     * 
     */
    public TFC.M1 createTFCM1() {
        return new TFC.M1();
    }

    /**
     * Create an instance of {@link TFC.O1 }
     * 
     */
    public TFC.O1 createTFCO1() {
        return new TFC.O1();
    }

    /**
     * Create an instance of {@link RSI.C1 }
     * 
     */
    public RSI.C1 createRSIC1() {
        return new RSI.C1();
    }

    /**
     * Create an instance of {@link RSI.Constant.Custom }
     * 
     */
    public RSI.Constant.Custom createRSIConstantCustom() {
        return new RSI.Constant.Custom();
    }

    /**
     * Create an instance of {@link RSI.O1 .Custom }
     * 
     */
    public RSI.O1 .Custom createRSIO1Custom() {
        return new RSI.O1 .Custom();
    }

    /**
     * Create an instance of {@link RSI.M4 .Custom }
     * 
     */
    public RSI.M4 .Custom createRSIM4Custom() {
        return new RSI.M4 .Custom();
    }

    /**
     * Create an instance of {@link RSI.M3 .Custom }
     * 
     */
    public RSI.M3 .Custom createRSIM3Custom() {
        return new RSI.M3 .Custom();
    }

    /**
     * Create an instance of {@link RSI.M1 .Custom }
     * 
     */
    public RSI.M1 .Custom createRSIM1Custom() {
        return new RSI.M1 .Custom();
    }

    /**
     * Create an instance of {@link RSI.D2 .Custom }
     * 
     */
    public RSI.D2 .Custom createRSID2Custom() {
        return new RSI.D2 .Custom();
    }

    /**
     * Create an instance of {@link RSI.C6 .Custom }
     * 
     */
    public RSI.C6 .Custom createRSIC6Custom() {
        return new RSI.C6 .Custom();
    }

    /**
     * Create an instance of {@link ISF.C1 }
     * 
     */
    public ISF.C1 createISFC1() {
        return new ISF.C1();
    }

    /**
     * Create an instance of {@link ISF.M1 }
     * 
     */
    public ISF.M1 createISFM1() {
        return new ISF.M1();
    }

    /**
     * Create an instance of {@link ISF.O1 .Custom }
     * 
     */
    public ISF.O1 .Custom createISFO1Custom() {
        return new ISF.O1 .Custom();
    }

    /**
     * Create an instance of {@link ISF.M3 .Custom }
     * 
     */
    public ISF.M3 .Custom createISFM3Custom() {
        return new ISF.M3 .Custom();
    }

    /**
     * Create an instance of {@link CFB.D2 }
     * 
     */
    public CFB.D2 createCFBD2() {
        return new CFB.D2();
    }

    /**
     * Create an instance of {@link CFB.C1 .Custom }
     * 
     */
    public CFB.C1 .Custom createCFBC1Custom() {
        return new CFB.C1 .Custom();
    }

    /**
     * Create an instance of {@link Accel.Open.Custom }
     * 
     */
    public Accel.Open.Custom createAccelOpenCustom() {
        return new Accel.Open.Custom();
    }

    /**
     * Create an instance of {@link Accel.Closed.Custom }
     * 
     */
    public Accel.Closed.Custom createAccelClosedCustom() {
        return new Accel.Closed.Custom();
    }

    /**
     * Create an instance of {@link LB.O1 .Custom }
     * 
     */
    public LB.O1 .Custom createLBO1Custom() {
        return new LB.O1 .Custom();
    }

    /**
     * Create an instance of {@link LB.C1 .Custom }
     * 
     */
    public LB.C1 .Custom createLBC1Custom() {
        return new LB.C1 .Custom();
    }

    /**
     * Create an instance of {@link FMC.Calculated }
     * 
     */
    public FMC.Calculated createFMCCalculated() {
        return new FMC.Calculated();
    }

    /**
     * Create an instance of {@link FMC.NotCalculated }
     * 
     */
    public FMC.NotCalculated createFMCNotCalculated() {
        return new FMC.NotCalculated();
    }

    /**
     * Create an instance of {@link FBPFuelType.IsModified.Growth }
     * 
     */
    public FBPFuelType.IsModified.Growth createFBPFuelTypeIsModifiedGrowth() {
        return new FBPFuelType.IsModified.Growth();
    }

    /**
     * Create an instance of {@link DailyCondition.SpecHour }
     * 
     */
    public DailyCondition.SpecHour createDailyConditionSpecHour() {
        return new DailyCondition.SpecHour();
    }

    /**
     * Create an instance of {@link DailyCondition.DayWeather }
     * 
     */
    public DailyCondition.DayWeather createDailyConditionDayWeather() {
        return new DailyCondition.DayWeather();
    }

    /**
     * Create an instance of {@link DailyCondition.HourWeather.HourData }
     * 
     */
    public DailyCondition.HourWeather.HourData createDailyConditionHourWeatherHourData() {
        return new DailyCondition.HourWeather.HourData();
    }

    /**
     * Create an instance of {@link WeatherStation.WeatherStreams }
     * 
     */
    public WeatherStation.WeatherStreams createWeatherStationWeatherStreams() {
        return new WeatherStation.WeatherStreams();
    }

    /**
     * Create an instance of {@link WeatherStream.StartingCodes }
     * 
     */
    public WeatherStream.StartingCodes createWeatherStreamStartingCodes() {
        return new WeatherStream.StartingCodes();
    }

    /**
     * Create an instance of {@link WeatherStream.Hffmc }
     * 
     */
    public WeatherStream.Hffmc createWeatherStreamHffmc() {
        return new WeatherStream.Hffmc();
    }

    /**
     * Create an instance of {@link WeatherStream.DailyConditions }
     * 
     */
    public WeatherStream.DailyConditions createWeatherStreamDailyConditions() {
        return new WeatherStream.DailyConditions();
    }

    /**
     * Create an instance of {@link WeatherStream.DiurnalParameters.Temperature }
     * 
     */
    public WeatherStream.DiurnalParameters.Temperature createWeatherStreamDiurnalParametersTemperature() {
        return new WeatherStream.DiurnalParameters.Temperature();
    }

    /**
     * Create an instance of {@link WeatherStream.DiurnalParameters.WindSpeed }
     * 
     */
    public WeatherStream.DiurnalParameters.WindSpeed createWeatherStreamDiurnalParametersWindSpeed() {
        return new WeatherStream.DiurnalParameters.WindSpeed();
    }

    /**
     * Create an instance of {@link WeatherGridData.DefaultSector }
     * 
     */
    public WeatherGridData.DefaultSector createWeatherGridDataDefaultSector() {
        return new WeatherGridData.DefaultSector();
    }

    /**
     * Create an instance of {@link WeatherGridData.Sectors.SectorList.Sector.SectorEntries }
     * 
     */
    public WeatherGridData.Sectors.SectorList.Sector.SectorEntries createWeatherGridDataSectorsSectorListSectorSectorEntries() {
        return new WeatherGridData.Sectors.SectorList.Sector.SectorEntries();
    }

    /**
     * Create an instance of {@link WeatherGridData.Sectors.SectorList.Sector.Direction.SpecificDirection }
     * 
     */
    public WeatherGridData.Sectors.SectorList.Sector.Direction.SpecificDirection createWeatherGridDataSectorsSectorListSectorDirectionSpecificDirection() {
        return new WeatherGridData.Sectors.SectorList.Sector.Direction.SpecificDirection();
    }

    /**
     * Create an instance of {@link WcsData.LocationFile }
     * 
     */
    public WcsData.LocationFile createWcsDataLocationFile() {
        return new WcsData.LocationFile();
    }

    /**
     * Create an instance of {@link WcsData.Contents }
     * 
     */
    public WcsData.Contents createWcsDataContents() {
        return new WcsData.Contents();
    }

    /**
     * Create an instance of {@link WcsData.Int8Data }
     * 
     */
    public WcsData.Int8Data createWcsDataInt8Data() {
        return new WcsData.Int8Data();
    }

    /**
     * Create an instance of {@link WcsData.Int16Data }
     * 
     */
    public WcsData.Int16Data createWcsDataInt16Data() {
        return new WcsData.Int16Data();
    }

    /**
     * Create an instance of {@link WcsData.Uint16Data }
     * 
     */
    public WcsData.Uint16Data createWcsDataUint16Data() {
        return new WcsData.Uint16Data();
    }

    /**
     * Create an instance of {@link WcsData.Uint8Data }
     * 
     */
    public WcsData.Uint8Data createWcsDataUint8Data() {
        return new WcsData.Uint8Data();
    }

    /**
     * Create an instance of {@link WcsData.Uint32Data }
     * 
     */
    public WcsData.Uint32Data createWcsDataUint32Data() {
        return new WcsData.Uint32Data();
    }

    /**
     * Create an instance of {@link WcsData.Uint64Data }
     * 
     */
    public WcsData.Uint64Data createWcsDataUint64Data() {
        return new WcsData.Uint64Data();
    }

    /**
     * Create an instance of {@link WcsData.Float32Data }
     * 
     */
    public WcsData.Float32Data createWcsDataFloat32Data() {
        return new WcsData.Float32Data();
    }

    /**
     * Create an instance of {@link WcsData.Int32Data }
     * 
     */
    public WcsData.Int32Data createWcsDataInt32Data() {
        return new WcsData.Int32Data();
    }

    /**
     * Create an instance of {@link WcsData.Int64Data }
     * 
     */
    public WcsData.Int64Data createWcsDataInt64Data() {
        return new WcsData.Int64Data();
    }

    /**
     * Create an instance of {@link WcsData.Float64Data }
     * 
     */
    public WcsData.Float64Data createWcsDataFloat64Data() {
        return new WcsData.Float64Data();
    }

    /**
     * Create an instance of {@link WfsData.LocationFile }
     * 
     */
    public WfsData.LocationFile createWfsDataLocationFile() {
        return new WfsData.LocationFile();
    }

    /**
     * Create an instance of {@link WfsData.VectorData.Point }
     * 
     */
    public WfsData.VectorData.Point createWfsDataVectorDataPoint() {
        return new WfsData.VectorData.Point();
    }

    /**
     * Create an instance of {@link WfsData.VectorData.Polyline }
     * 
     */
    public WfsData.VectorData.Polyline createWfsDataVectorDataPolyline() {
        return new WfsData.VectorData.Polyline();
    }

    /**
     * Create an instance of {@link WfsData.VectorData.Polygon }
     * 
     */
    public WfsData.VectorData.Polygon createWfsDataVectorDataPolygon() {
        return new WfsData.VectorData.Polygon();
    }

    /**
     * Create an instance of {@link Data.Job.Extra }
     * 
     */
    public Data.Job.Extra createDataJobExtra() {
        return new Data.Job.Extra();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.WeatherStations }
     * 
     */
    public Data.Job.Inputs.WeatherStations createDataJobInputsWeatherStations() {
        return new Data.Job.Inputs.WeatherStations();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Timezone }
     * 
     */
    public Data.Job.Inputs.Timezone createDataJobInputsTimezone() {
        return new Data.Job.Inputs.Timezone();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.FgmOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.FgmOptions createDataJobInputsScenariosScenarioCopyFgmOptions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.FgmOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.FbpOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.FbpOptions createDataJobInputsScenariosScenarioCopyFbpOptions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.FbpOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.FmcOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.FmcOptions createDataJobInputsScenariosScenarioCopyFmcOptions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.FmcOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.FwiOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.FwiOptions createDataJobInputsScenariosScenarioCopyFwiOptions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.FwiOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.BurningConditions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.BurningConditions createDataJobInputsScenariosScenarioCopyBurningConditions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.BurningConditions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.TemporalStateConditions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.TemporalStateConditions createDataJobInputsScenariosScenarioCopyTemporalStateConditions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.TemporalStateConditions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.PercentileOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.PercentileOptions createDataJobInputsScenariosScenarioCopyPercentileOptions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.PercentileOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.VectorInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.VectorInfo createDataJobInputsScenariosScenarioCopyVectorInfo() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.VectorInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.IgnitionInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.IgnitionInfo createDataJobInputsScenariosScenarioCopyIgnitionInfo() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.IgnitionInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.WxOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.WxOptions createDataJobInputsScenariosScenarioCopyWxOptions() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.WxOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.StreamInfo.StreamName }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.StreamInfo.StreamName createDataJobInputsScenariosScenarioCopyStreamInfoStreamName() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.StreamInfo.StreamName();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.ScenarioCopy.LayerInfo.Filter }
     * 
     */
    public Data.Job.Inputs.Scenarios.ScenarioCopy.LayerInfo.Filter createDataJobInputsScenariosScenarioCopyLayerInfoFilter() {
        return new Data.Job.Inputs.Scenarios.ScenarioCopy.LayerInfo.Filter();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.FgmOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.FgmOptions createDataJobInputsScenariosScenarioFgmOptions() {
        return new Data.Job.Inputs.Scenarios.Scenario.FgmOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.FbpOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.FbpOptions createDataJobInputsScenariosScenarioFbpOptions() {
        return new Data.Job.Inputs.Scenarios.Scenario.FbpOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.FmcOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.FmcOptions createDataJobInputsScenariosScenarioFmcOptions() {
        return new Data.Job.Inputs.Scenarios.Scenario.FmcOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.FwiOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.FwiOptions createDataJobInputsScenariosScenarioFwiOptions() {
        return new Data.Job.Inputs.Scenarios.Scenario.FwiOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.BurningConditions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.BurningConditions createDataJobInputsScenariosScenarioBurningConditions() {
        return new Data.Job.Inputs.Scenarios.Scenario.BurningConditions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.TemporalStateConditions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.TemporalStateConditions createDataJobInputsScenariosScenarioTemporalStateConditions() {
        return new Data.Job.Inputs.Scenarios.Scenario.TemporalStateConditions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.PercentileOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.PercentileOptions createDataJobInputsScenariosScenarioPercentileOptions() {
        return new Data.Job.Inputs.Scenarios.Scenario.PercentileOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.VectorInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.VectorInfo createDataJobInputsScenariosScenarioVectorInfo() {
        return new Data.Job.Inputs.Scenarios.Scenario.VectorInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.IgnitionInfo }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.IgnitionInfo createDataJobInputsScenariosScenarioIgnitionInfo() {
        return new Data.Job.Inputs.Scenarios.Scenario.IgnitionInfo();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.WxOptions }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.WxOptions createDataJobInputsScenariosScenarioWxOptions() {
        return new Data.Job.Inputs.Scenarios.Scenario.WxOptions();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.StreamInfo.StreamName }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.StreamInfo.StreamName createDataJobInputsScenariosScenarioStreamInfoStreamName() {
        return new Data.Job.Inputs.Scenarios.Scenario.StreamInfo.StreamName();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Scenarios.Scenario.LayerInfo.Filter }
     * 
     */
    public Data.Job.Inputs.Scenarios.Scenario.LayerInfo.Filter createDataJobInputsScenariosScenarioLayerInfoFilter() {
        return new Data.Job.Inputs.Scenarios.Scenario.LayerInfo.Filter();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Ignitions.Ignition.Coordinates }
     * 
     */
    public Data.Job.Inputs.Ignitions.Ignition.Coordinates createDataJobInputsIgnitionsIgnitionCoordinates() {
        return new Data.Job.Inputs.Ignitions.Ignition.Coordinates();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.ProjectionFile }
     * 
     */
    public Data.Job.Inputs.Files.ProjectionFile createDataJobInputsFilesProjectionFile() {
        return new Data.Job.Inputs.Files.ProjectionFile();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelmapFile }
     * 
     */
    public Data.Job.Inputs.Files.FuelmapFile createDataJobInputsFilesFuelmapFile() {
        return new Data.Job.Inputs.Files.FuelmapFile();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.ElevationFile }
     * 
     */
    public Data.Job.Inputs.Files.ElevationFile createDataJobInputsFilesElevationFile() {
        return new Data.Job.Inputs.Files.ElevationFile();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherGridFiles }
     * 
     */
    public Data.Job.Inputs.Files.WeatherGridFiles createDataJobInputsFilesWeatherGridFiles() {
        return new Data.Job.Inputs.Files.WeatherGridFiles();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Temperature }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Temperature createDataJobInputsFilesWeatherPatchFilesPatchFileTemperature() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Temperature();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Rh }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Rh createDataJobInputsFilesWeatherPatchFilesPatchFileRh() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Rh();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Precipitation }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Precipitation createDataJobInputsFilesWeatherPatchFilesPatchFilePrecipitation() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Precipitation();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.WindSpeed }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.WindSpeed createDataJobInputsFilesWeatherPatchFilesPatchFileWindSpeed() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.WindSpeed();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.WindDirection }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.WindDirection createDataJobInputsFilesWeatherPatchFilesPatchFileWindDirection() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.WindDirection();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Geographic.Coordinates }
     * 
     */
    public Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Geographic.Coordinates createDataJobInputsFilesWeatherPatchFilesPatchFileGeographicCoordinates() {
        return new Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Geographic.Coordinates();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.GridFiles.GridFile.GridFileData }
     * 
     */
    public Data.Job.Inputs.Files.GridFiles.GridFile.GridFileData createDataJobInputsFilesGridFilesGridFileGridFileData() {
        return new Data.Job.Inputs.Files.GridFiles.GridFile.GridFileData();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.FromFuel }
     * 
     */
    public Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.FromFuel createDataJobInputsFilesFuelPatchFilesFuelPatchFileFromFuel() {
        return new Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.FromFuel();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic.Coordinates }
     * 
     */
    public Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic.Coordinates createDataJobInputsFilesFuelPatchFilesFuelPatchFileGeographicCoordinates() {
        return new Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic.Coordinates();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic.Bounded }
     * 
     */
    public Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic.Bounded createDataJobInputsFilesFuelPatchFilesFuelPatchFileGeographicBounded() {
        return new Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic.Bounded();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.FuelbreakFiles.FuelbreakFile }
     * 
     */
    public Data.Job.Inputs.Files.FuelbreakFiles.FuelbreakFile createDataJobInputsFilesFuelbreakFilesFuelbreakFile() {
        return new Data.Job.Inputs.Files.FuelbreakFiles.FuelbreakFile();
    }

    /**
     * Create an instance of {@link Data.Job.Inputs.Files.LutFile.FuelType }
     * 
     */
    public Data.Job.Inputs.Files.LutFile.FuelType createDataJobInputsFilesLutFileFuelType() {
        return new Data.Job.Inputs.Files.LutFile.FuelType();
    }

    /**
     * Create an instance of {@link Data.Params.Log }
     * 
     */
    public Data.Params.Log createDataParamsLog() {
        return new Data.Params.Log();
    }

    /**
     * Create an instance of {@link Data.Params.Signals }
     * 
     */
    public Data.Params.Signals createDataParamsSignals() {
        return new Data.Params.Signals();
    }

    /**
     * Create an instance of {@link Data.Params.Hardware }
     * 
     */
    public Data.Params.Hardware createDataParamsHardware() {
        return new Data.Params.Hardware();
    }

    /**
     * Create an instance of {@link Defaults.Job.FgmOptions }
     * 
     */
    public Defaults.Job.FgmOptions createDefaultsJobFgmOptions() {
        return new Defaults.Job.FgmOptions();
    }

    /**
     * Create an instance of {@link Defaults.Job.FbpOptions }
     * 
     */
    public Defaults.Job.FbpOptions createDefaultsJobFbpOptions() {
        return new Defaults.Job.FbpOptions();
    }

    /**
     * Create an instance of {@link Defaults.Job.FmcOptions }
     * 
     */
    public Defaults.Job.FmcOptions createDefaultsJobFmcOptions() {
        return new Defaults.Job.FmcOptions();
    }

    /**
     * Create an instance of {@link Defaults.Job.FwiOptions }
     * 
     */
    public Defaults.Job.FwiOptions createDefaultsJobFwiOptions() {
        return new Defaults.Job.FwiOptions();
    }

    /**
     * Create an instance of {@link Defaults.Job.VectorFile.Metadata }
     * 
     */
    public Defaults.Job.VectorFile.Metadata createDefaultsJobVectorFileMetadata() {
        return new Defaults.Job.VectorFile.Metadata();
    }

}
