//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.10 at 10:49:01 AM CST 
//


package ca.wise.fgm.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for outputs complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outputs"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="summaryFiles" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="summary" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="outputApplication" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputGeoData" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputScenario" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputScenarioComments" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputInputs" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputLandscape" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputFBPPatches" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputWxPatches" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputIgnitions" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputWxStreams" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="outputFBP" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vectorFiles" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="vectorFile" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="metadata"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="jobName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="igName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="simDate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="fireSize" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="perimTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="perimActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                     &lt;attribute name="areaUnit"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                           &lt;enumeration value="KM2"/&gt;
 *                                           &lt;enumeration value="M2"/&gt;
 *                                           &lt;enumeration value="HA"/&gt;
 *                                           &lt;enumeration value="MI2"/&gt;
 *                                           &lt;enumeration value="FT2"/&gt;
 *                                           &lt;enumeration value="YD2"/&gt;
 *                                           &lt;enumeration value="ACRE"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                     &lt;attribute name="perimUnit"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                           &lt;enumeration value="KM"/&gt;
 *                                           &lt;enumeration value="M"/&gt;
 *                                           &lt;enumeration value="MI"/&gt;
 *                                           &lt;enumeration value="FT"/&gt;
 *                                           &lt;enumeration value="YARD"/&gt;
 *                                           &lt;enumeration value="CHAIN"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="perimTime"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="startTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                                     &lt;attribute name="endTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="multiplePerim" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="removeIslands" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="mergeContact" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="perimActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="gridFiles" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="gridFile" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="exportTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                           &lt;attribute name="interpolationMethod" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;enumeration value="ClosestVertex"/&gt;
 *                                 &lt;enumeration value="IDW"/&gt;
 *                                 &lt;enumeration value="AreaWeighting"/&gt;
 *                                 &lt;enumeration value="Calculate"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="statistic" use="required"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;enumeration value="TEMP"/&gt;
 *                                 &lt;enumeration value="DP"/&gt;
 *                                 &lt;enumeration value="RH"/&gt;
 *                                 &lt;enumeration value="WDIR"/&gt;
 *                                 &lt;enumeration value="WS"/&gt;
 *                                 &lt;enumeration value="PRECIP"/&gt;
 *                                 &lt;enumeration value="FFMC"/&gt;
 *                                 &lt;enumeration value="ISI"/&gt;
 *                                 &lt;enumeration value="FWI"/&gt;
 *                                 &lt;enumeration value="BUI"/&gt;
 *                                 &lt;enumeration value="FI"/&gt;
 *                                 &lt;enumeration value="FL"/&gt;
 *                                 &lt;enumeration value="ROS"/&gt;
 *                                 &lt;enumeration value="SFC"/&gt;
 *                                 &lt;enumeration value="CFC"/&gt;
 *                                 &lt;enumeration value="TFC"/&gt;
 *                                 &lt;enumeration value="CFB"/&gt;
 *                                 &lt;enumeration value="RAZ"/&gt;
 *                                 &lt;enumeration value="BURNGRID"/&gt;
 *                                 &lt;enumeration value="FIREARRIVALTIME"/&gt;
 *                                 &lt;enumeration value="HROS"/&gt;
 *                                 &lt;enumeration value="FROS"/&gt;
 *                                 &lt;enumeration value="BROS"/&gt;
 *                                 &lt;enumeration value="RSS"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                           &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outputs", namespace = "Outputs_Schema", propOrder = {

})
public class Outputs {

    @XmlElement(namespace = "Outputs_Schema")
    protected Outputs.SummaryFiles summaryFiles;
    @XmlElement(namespace = "Outputs_Schema")
    protected Outputs.VectorFiles vectorFiles;
    @XmlElement(namespace = "Outputs_Schema")
    protected Outputs.GridFiles gridFiles;

    /**
     * Gets the value of the summaryFiles property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs.SummaryFiles }
     *     
     */
    public Outputs.SummaryFiles getSummaryFiles() {
        return summaryFiles;
    }

    /**
     * Sets the value of the summaryFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs.SummaryFiles }
     *     
     */
    public void setSummaryFiles(Outputs.SummaryFiles value) {
        this.summaryFiles = value;
    }

    /**
     * Gets the value of the vectorFiles property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs.VectorFiles }
     *     
     */
    public Outputs.VectorFiles getVectorFiles() {
        return vectorFiles;
    }

    /**
     * Sets the value of the vectorFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs.VectorFiles }
     *     
     */
    public void setVectorFiles(Outputs.VectorFiles value) {
        this.vectorFiles = value;
    }

    /**
     * Gets the value of the gridFiles property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs.GridFiles }
     *     
     */
    public Outputs.GridFiles getGridFiles() {
        return gridFiles;
    }

    /**
     * Sets the value of the gridFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs.GridFiles }
     *     
     */
    public void setGridFiles(Outputs.GridFiles value) {
        this.gridFiles = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="gridFile" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="exportTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *                 &lt;attribute name="interpolationMethod" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;enumeration value="ClosestVertex"/&gt;
     *                       &lt;enumeration value="IDW"/&gt;
     *                       &lt;enumeration value="AreaWeighting"/&gt;
     *                       &lt;enumeration value="Calculate"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="statistic" use="required"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;enumeration value="TEMP"/&gt;
     *                       &lt;enumeration value="DP"/&gt;
     *                       &lt;enumeration value="RH"/&gt;
     *                       &lt;enumeration value="WDIR"/&gt;
     *                       &lt;enumeration value="WS"/&gt;
     *                       &lt;enumeration value="PRECIP"/&gt;
     *                       &lt;enumeration value="FFMC"/&gt;
     *                       &lt;enumeration value="ISI"/&gt;
     *                       &lt;enumeration value="FWI"/&gt;
     *                       &lt;enumeration value="BUI"/&gt;
     *                       &lt;enumeration value="FI"/&gt;
     *                       &lt;enumeration value="FL"/&gt;
     *                       &lt;enumeration value="ROS"/&gt;
     *                       &lt;enumeration value="SFC"/&gt;
     *                       &lt;enumeration value="CFC"/&gt;
     *                       &lt;enumeration value="TFC"/&gt;
     *                       &lt;enumeration value="CFB"/&gt;
     *                       &lt;enumeration value="RAZ"/&gt;
     *                       &lt;enumeration value="BURNGRID"/&gt;
     *                       &lt;enumeration value="FIREARRIVALTIME"/&gt;
     *                       &lt;enumeration value="HROS"/&gt;
     *                       &lt;enumeration value="FROS"/&gt;
     *                       &lt;enumeration value="BROS"/&gt;
     *                       &lt;enumeration value="RSS"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *                 &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gridFile"
    })
    public static class GridFiles {

        @XmlElement(namespace = "Outputs_Schema", required = true)
        protected List<Outputs.GridFiles.GridFile> gridFile;

        /**
         * Gets the value of the gridFile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gridFile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGridFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Outputs.GridFiles.GridFile }
         * 
         * 
         */
        public List<Outputs.GridFiles.GridFile> getGridFile() {
            if (gridFile == null) {
                gridFile = new ArrayList<Outputs.GridFiles.GridFile>();
            }
            return this.gridFile;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="exportTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *       &lt;attribute name="interpolationMethod" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;enumeration value="ClosestVertex"/&gt;
         *             &lt;enumeration value="IDW"/&gt;
         *             &lt;enumeration value="AreaWeighting"/&gt;
         *             &lt;enumeration value="Calculate"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="statistic" use="required"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;enumeration value="TEMP"/&gt;
         *             &lt;enumeration value="DP"/&gt;
         *             &lt;enumeration value="RH"/&gt;
         *             &lt;enumeration value="WDIR"/&gt;
         *             &lt;enumeration value="WS"/&gt;
         *             &lt;enumeration value="PRECIP"/&gt;
         *             &lt;enumeration value="FFMC"/&gt;
         *             &lt;enumeration value="ISI"/&gt;
         *             &lt;enumeration value="FWI"/&gt;
         *             &lt;enumeration value="BUI"/&gt;
         *             &lt;enumeration value="FI"/&gt;
         *             &lt;enumeration value="FL"/&gt;
         *             &lt;enumeration value="ROS"/&gt;
         *             &lt;enumeration value="SFC"/&gt;
         *             &lt;enumeration value="CFC"/&gt;
         *             &lt;enumeration value="TFC"/&gt;
         *             &lt;enumeration value="CFB"/&gt;
         *             &lt;enumeration value="RAZ"/&gt;
         *             &lt;enumeration value="BURNGRID"/&gt;
         *             &lt;enumeration value="FIREARRIVALTIME"/&gt;
         *             &lt;enumeration value="HROS"/&gt;
         *             &lt;enumeration value="FROS"/&gt;
         *             &lt;enumeration value="BROS"/&gt;
         *             &lt;enumeration value="RSS"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *       &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GridFile {

            @XmlAttribute(name = "fileName", required = true)
            protected String fileName;
            @XmlAttribute(name = "exportTime", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar exportTime;
            @XmlAttribute(name = "interpolationMethod", required = true)
            protected String interpolationMethod;
            @XmlAttribute(name = "statistic", required = true)
            protected String statistic;
            @XmlAttribute(name = "scenName", required = true)
            protected String scenName;

            /**
             * Gets the value of the fileName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

            /**
             * Gets the value of the exportTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getExportTime() {
                return exportTime;
            }

            /**
             * Sets the value of the exportTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setExportTime(XMLGregorianCalendar value) {
                this.exportTime = value;
            }

            /**
             * Gets the value of the interpolationMethod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInterpolationMethod() {
                return interpolationMethod;
            }

            /**
             * Sets the value of the interpolationMethod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInterpolationMethod(String value) {
                this.interpolationMethod = value;
            }

            /**
             * Gets the value of the statistic property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatistic() {
                return statistic;
            }

            /**
             * Sets the value of the statistic property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatistic(String value) {
                this.statistic = value;
            }

            /**
             * Gets the value of the scenName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScenName() {
                return scenName;
            }

            /**
             * Sets the value of the scenName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScenName(String value) {
                this.scenName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="summary" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="outputApplication" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputGeoData" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputScenario" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputScenarioComments" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputInputs" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputLandscape" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputFBPPatches" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputWxPatches" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputIgnitions" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputWxStreams" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="outputFBP" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "summary"
    })
    public static class SummaryFiles {

        @XmlElement(namespace = "Outputs_Schema", required = true)
        protected List<Outputs.SummaryFiles.Summary> summary;

        /**
         * Gets the value of the summary property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the summary property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSummary().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Outputs.SummaryFiles.Summary }
         * 
         * 
         */
        public List<Outputs.SummaryFiles.Summary> getSummary() {
            if (summary == null) {
                summary = new ArrayList<Outputs.SummaryFiles.Summary>();
            }
            return this.summary;
        }


        /**
         * Contents of summary file.
         * 
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="outputApplication" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputGeoData" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputScenario" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputScenarioComments" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputInputs" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputLandscape" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputFBPPatches" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputWxPatches" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputIgnitions" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputWxStreams" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="outputFBP" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Summary {

            @XmlAttribute(name = "scenName", required = true)
            protected String scenName;
            @XmlAttribute(name = "outputApplication")
            protected Boolean outputApplication;
            @XmlAttribute(name = "outputGeoData")
            protected Boolean outputGeoData;
            @XmlAttribute(name = "outputScenario")
            protected Boolean outputScenario;
            @XmlAttribute(name = "outputScenarioComments")
            protected Boolean outputScenarioComments;
            @XmlAttribute(name = "outputInputs")
            protected Boolean outputInputs;
            @XmlAttribute(name = "outputLandscape")
            protected Boolean outputLandscape;
            @XmlAttribute(name = "outputFBPPatches")
            protected Boolean outputFBPPatches;
            @XmlAttribute(name = "outputWxPatches")
            protected Boolean outputWxPatches;
            @XmlAttribute(name = "outputIgnitions")
            protected Boolean outputIgnitions;
            @XmlAttribute(name = "outputWxStreams")
            protected Boolean outputWxStreams;
            @XmlAttribute(name = "outputFBP")
            protected Boolean outputFBP;
            @XmlAttribute(name = "fileName", required = true)
            protected String fileName;

            /**
             * Gets the value of the scenName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScenName() {
                return scenName;
            }

            /**
             * Sets the value of the scenName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScenName(String value) {
                this.scenName = value;
            }

            /**
             * Gets the value of the outputApplication property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputApplication() {
                return outputApplication;
            }

            /**
             * Sets the value of the outputApplication property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputApplication(Boolean value) {
                this.outputApplication = value;
            }

            /**
             * Gets the value of the outputGeoData property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputGeoData() {
                return outputGeoData;
            }

            /**
             * Sets the value of the outputGeoData property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputGeoData(Boolean value) {
                this.outputGeoData = value;
            }

            /**
             * Gets the value of the outputScenario property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputScenario() {
                return outputScenario;
            }

            /**
             * Sets the value of the outputScenario property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputScenario(Boolean value) {
                this.outputScenario = value;
            }

            /**
             * Gets the value of the outputScenarioComments property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputScenarioComments() {
                return outputScenarioComments;
            }

            /**
             * Sets the value of the outputScenarioComments property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputScenarioComments(Boolean value) {
                this.outputScenarioComments = value;
            }

            /**
             * Gets the value of the outputInputs property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputInputs() {
                return outputInputs;
            }

            /**
             * Sets the value of the outputInputs property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputInputs(Boolean value) {
                this.outputInputs = value;
            }

            /**
             * Gets the value of the outputLandscape property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputLandscape() {
                return outputLandscape;
            }

            /**
             * Sets the value of the outputLandscape property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputLandscape(Boolean value) {
                this.outputLandscape = value;
            }

            /**
             * Gets the value of the outputFBPPatches property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputFBPPatches() {
                return outputFBPPatches;
            }

            /**
             * Sets the value of the outputFBPPatches property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputFBPPatches(Boolean value) {
                this.outputFBPPatches = value;
            }

            /**
             * Gets the value of the outputWxPatches property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputWxPatches() {
                return outputWxPatches;
            }

            /**
             * Sets the value of the outputWxPatches property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputWxPatches(Boolean value) {
                this.outputWxPatches = value;
            }

            /**
             * Gets the value of the outputIgnitions property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputIgnitions() {
                return outputIgnitions;
            }

            /**
             * Sets the value of the outputIgnitions property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputIgnitions(Boolean value) {
                this.outputIgnitions = value;
            }

            /**
             * Gets the value of the outputWxStreams property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputWxStreams() {
                return outputWxStreams;
            }

            /**
             * Sets the value of the outputWxStreams property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputWxStreams(Boolean value) {
                this.outputWxStreams = value;
            }

            /**
             * Gets the value of the outputFBP property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isOutputFBP() {
                return outputFBP;
            }

            /**
             * Sets the value of the outputFBP property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setOutputFBP(Boolean value) {
                this.outputFBP = value;
            }

            /**
             * Gets the value of the fileName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="vectorFile" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="metadata"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="jobName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="igName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="simDate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="fireSize" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="perimTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="perimActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                           &lt;attribute name="areaUnit"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                 &lt;enumeration value="KM2"/&gt;
     *                                 &lt;enumeration value="M2"/&gt;
     *                                 &lt;enumeration value="HA"/&gt;
     *                                 &lt;enumeration value="MI2"/&gt;
     *                                 &lt;enumeration value="FT2"/&gt;
     *                                 &lt;enumeration value="YD2"/&gt;
     *                                 &lt;enumeration value="ACRE"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                           &lt;attribute name="perimUnit"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                 &lt;enumeration value="KM"/&gt;
     *                                 &lt;enumeration value="M"/&gt;
     *                                 &lt;enumeration value="MI"/&gt;
     *                                 &lt;enumeration value="FT"/&gt;
     *                                 &lt;enumeration value="YARD"/&gt;
     *                                 &lt;enumeration value="CHAIN"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="perimTime"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="startTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *                           &lt;attribute name="endTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="multiplePerim" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="removeIslands" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="mergeContact" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="perimActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vectorFile"
    })
    public static class VectorFiles {

        @XmlElement(namespace = "Outputs_Schema", required = true)
        protected List<Outputs.VectorFiles.VectorFile> vectorFile;

        /**
         * Gets the value of the vectorFile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vectorFile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVectorFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Outputs.VectorFiles.VectorFile }
         * 
         * 
         */
        public List<Outputs.VectorFiles.VectorFile> getVectorFile() {
            if (vectorFile == null) {
                vectorFile = new ArrayList<Outputs.VectorFiles.VectorFile>();
            }
            return this.vectorFile;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="metadata"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="jobName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="igName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="simDate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="fireSize" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="perimTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="perimActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *                 &lt;attribute name="areaUnit"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                       &lt;enumeration value="KM2"/&gt;
         *                       &lt;enumeration value="M2"/&gt;
         *                       &lt;enumeration value="HA"/&gt;
         *                       &lt;enumeration value="MI2"/&gt;
         *                       &lt;enumeration value="FT2"/&gt;
         *                       &lt;enumeration value="YD2"/&gt;
         *                       &lt;enumeration value="ACRE"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *                 &lt;attribute name="perimUnit"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                       &lt;enumeration value="KM"/&gt;
         *                       &lt;enumeration value="M"/&gt;
         *                       &lt;enumeration value="MI"/&gt;
         *                       &lt;enumeration value="FT"/&gt;
         *                       &lt;enumeration value="YARD"/&gt;
         *                       &lt;enumeration value="CHAIN"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="perimTime"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="startTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *                 &lt;attribute name="endTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="multiplePerim" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="removeIslands" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="mergeContact" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="perimActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "metadata",
            "perimTime"
        })
        public static class VectorFile {

            @XmlElement(namespace = "Outputs_Schema", required = true)
            protected Outputs.VectorFiles.VectorFile.Metadata metadata;
            @XmlElement(namespace = "Outputs_Schema", required = true)
            protected Outputs.VectorFiles.VectorFile.PerimTime perimTime;
            @XmlAttribute(name = "fileName", required = true)
            protected String fileName;
            @XmlAttribute(name = "multiplePerim", required = true)
            protected boolean multiplePerim;
            @XmlAttribute(name = "removeIslands", required = true)
            protected boolean removeIslands;
            @XmlAttribute(name = "mergeContact", required = true)
            protected boolean mergeContact;
            @XmlAttribute(name = "perimActive", required = true)
            protected boolean perimActive;
            @XmlAttribute(name = "scenName", required = true)
            protected String scenName;

            /**
             * Gets the value of the metadata property.
             * 
             * @return
             *     possible object is
             *     {@link Outputs.VectorFiles.VectorFile.Metadata }
             *     
             */
            public Outputs.VectorFiles.VectorFile.Metadata getMetadata() {
                return metadata;
            }

            /**
             * Sets the value of the metadata property.
             * 
             * @param value
             *     allowed object is
             *     {@link Outputs.VectorFiles.VectorFile.Metadata }
             *     
             */
            public void setMetadata(Outputs.VectorFiles.VectorFile.Metadata value) {
                this.metadata = value;
            }

            /**
             * Gets the value of the perimTime property.
             * 
             * @return
             *     possible object is
             *     {@link Outputs.VectorFiles.VectorFile.PerimTime }
             *     
             */
            public Outputs.VectorFiles.VectorFile.PerimTime getPerimTime() {
                return perimTime;
            }

            /**
             * Sets the value of the perimTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Outputs.VectorFiles.VectorFile.PerimTime }
             *     
             */
            public void setPerimTime(Outputs.VectorFiles.VectorFile.PerimTime value) {
                this.perimTime = value;
            }

            /**
             * Gets the value of the fileName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

            /**
             * Gets the value of the multiplePerim property.
             * 
             */
            public boolean isMultiplePerim() {
                return multiplePerim;
            }

            /**
             * Sets the value of the multiplePerim property.
             * 
             */
            public void setMultiplePerim(boolean value) {
                this.multiplePerim = value;
            }

            /**
             * Gets the value of the removeIslands property.
             * 
             */
            public boolean isRemoveIslands() {
                return removeIslands;
            }

            /**
             * Sets the value of the removeIslands property.
             * 
             */
            public void setRemoveIslands(boolean value) {
                this.removeIslands = value;
            }

            /**
             * Gets the value of the mergeContact property.
             * 
             */
            public boolean isMergeContact() {
                return mergeContact;
            }

            /**
             * Sets the value of the mergeContact property.
             * 
             */
            public void setMergeContact(boolean value) {
                this.mergeContact = value;
            }

            /**
             * Gets the value of the perimActive property.
             * 
             */
            public boolean isPerimActive() {
                return perimActive;
            }

            /**
             * Sets the value of the perimActive property.
             * 
             */
            public void setPerimActive(boolean value) {
                this.perimActive = value;
            }

            /**
             * Gets the value of the scenName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScenName() {
                return scenName;
            }

            /**
             * Sets the value of the scenName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScenName(String value) {
                this.scenName = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected         content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="scenName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="jobName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="igName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="simDate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="fireSize" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="perimTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="perimActive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *       &lt;attribute name="areaUnit"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *             &lt;enumeration value="KM2"/&gt;
             *             &lt;enumeration value="M2"/&gt;
             *             &lt;enumeration value="HA"/&gt;
             *             &lt;enumeration value="MI2"/&gt;
             *             &lt;enumeration value="FT2"/&gt;
             *             &lt;enumeration value="YD2"/&gt;
             *             &lt;enumeration value="ACRE"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *       &lt;attribute name="perimUnit"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *             &lt;enumeration value="KM"/&gt;
             *             &lt;enumeration value="M"/&gt;
             *             &lt;enumeration value="MI"/&gt;
             *             &lt;enumeration value="FT"/&gt;
             *             &lt;enumeration value="YARD"/&gt;
             *             &lt;enumeration value="CHAIN"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Metadata {

                @XmlAttribute(name = "version", required = true)
                protected boolean version;
                @XmlAttribute(name = "scenName", required = true)
                protected boolean scenName;
                @XmlAttribute(name = "jobName", required = true)
                protected boolean jobName;
                @XmlAttribute(name = "igName", required = true)
                protected boolean igName;
                @XmlAttribute(name = "simDate", required = true)
                protected boolean simDate;
                @XmlAttribute(name = "fireSize", required = true)
                protected boolean fireSize;
                @XmlAttribute(name = "perimTotal", required = true)
                protected boolean perimTotal;
                @XmlAttribute(name = "perimActive", required = true)
                protected boolean perimActive;
                @XmlAttribute(name = "areaUnit")
                protected String areaUnit;
                @XmlAttribute(name = "perimUnit")
                protected String perimUnit;

                /**
                 * Gets the value of the version property.
                 * 
                 */
                public boolean isVersion() {
                    return version;
                }

                /**
                 * Sets the value of the version property.
                 * 
                 */
                public void setVersion(boolean value) {
                    this.version = value;
                }

                /**
                 * Gets the value of the scenName property.
                 * 
                 */
                public boolean isScenName() {
                    return scenName;
                }

                /**
                 * Sets the value of the scenName property.
                 * 
                 */
                public void setScenName(boolean value) {
                    this.scenName = value;
                }

                /**
                 * Gets the value of the jobName property.
                 * 
                 */
                public boolean isJobName() {
                    return jobName;
                }

                /**
                 * Sets the value of the jobName property.
                 * 
                 */
                public void setJobName(boolean value) {
                    this.jobName = value;
                }

                /**
                 * Gets the value of the igName property.
                 * 
                 */
                public boolean isIgName() {
                    return igName;
                }

                /**
                 * Sets the value of the igName property.
                 * 
                 */
                public void setIgName(boolean value) {
                    this.igName = value;
                }

                /**
                 * Gets the value of the simDate property.
                 * 
                 */
                public boolean isSimDate() {
                    return simDate;
                }

                /**
                 * Sets the value of the simDate property.
                 * 
                 */
                public void setSimDate(boolean value) {
                    this.simDate = value;
                }

                /**
                 * Gets the value of the fireSize property.
                 * 
                 */
                public boolean isFireSize() {
                    return fireSize;
                }

                /**
                 * Sets the value of the fireSize property.
                 * 
                 */
                public void setFireSize(boolean value) {
                    this.fireSize = value;
                }

                /**
                 * Gets the value of the perimTotal property.
                 * 
                 */
                public boolean isPerimTotal() {
                    return perimTotal;
                }

                /**
                 * Sets the value of the perimTotal property.
                 * 
                 */
                public void setPerimTotal(boolean value) {
                    this.perimTotal = value;
                }

                /**
                 * Gets the value of the perimActive property.
                 * 
                 */
                public boolean isPerimActive() {
                    return perimActive;
                }

                /**
                 * Sets the value of the perimActive property.
                 * 
                 */
                public void setPerimActive(boolean value) {
                    this.perimActive = value;
                }

                /**
                 * Gets the value of the areaUnit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAreaUnit() {
                    return areaUnit;
                }

                /**
                 * Sets the value of the areaUnit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAreaUnit(String value) {
                    this.areaUnit = value;
                }

                /**
                 * Gets the value of the perimUnit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPerimUnit() {
                    return perimUnit;
                }

                /**
                 * Sets the value of the perimUnit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPerimUnit(String value) {
                    this.perimUnit = value;
                }

            }


            /**
             * Output perimeter time.
             * 
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected         content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="startTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
             *       &lt;attribute name="endTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PerimTime {

                @XmlAttribute(name = "startTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar startTime;
                @XmlAttribute(name = "endTime", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar endTime;

                /**
                 * Gets the value of the startTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getStartTime() {
                    return startTime;
                }

                /**
                 * Sets the value of the startTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setStartTime(XMLGregorianCalendar value) {
                    this.startTime = value;
                }

                /**
                 * Gets the value of the endTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getEndTime() {
                    return endTime;
                }

                /**
                 * Sets the value of the endTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setEndTime(XMLGregorianCalendar value) {
                    this.endTime = value;
                }

            }

        }

    }

}
