//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.10 at 10:49:01 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.heartlandsoftware.ca/xml/types")
package ca.wise.fgm.xml;
