//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.10.08 at 07:03:29 PM CDT 
//


package ca.wise.fgm.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RSI complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RSI"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="C1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="C1"/&gt;
 *                         &lt;enumeration value="NonFuel"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="C6"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="C6"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Eq61_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq61_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq61_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq61_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq61_P5" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq61_P6" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq64_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq64_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq64_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="D2"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="D2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="BUI_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Scale1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Scale2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="M1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="M1"/&gt;
 *                         &lt;enumeration value="M2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="M3"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="M3"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M3_C2_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M3_C2_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M3_C2_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="M4"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="M4"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M3_C2_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M3_C2_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M3_C2_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M4_D1_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M4_D1_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="M4_D1_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="O1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="O1a"/&gt;
 *                         &lt;enumeration value="O1b"/&gt;
 *                         &lt;enumeration value="O1ab"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="C_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq35a_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq35a_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq35b_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq35b_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Constant"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="RSI" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="NZ70"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RSI", namespace = "FBP_Schema", propOrder = {
    "c1",
    "c6",
    "d2",
    "m1",
    "m3",
    "m4",
    "o1",
    "constant"
})
public class RSI {

    @XmlElement(name = "C1", namespace = "FBP_Schema")
    protected RSI.C1 c1;
    @XmlElement(name = "C6", namespace = "FBP_Schema")
    protected RSI.C6 c6;
    @XmlElement(name = "D2", namespace = "FBP_Schema")
    protected RSI.D2 d2;
    @XmlElement(name = "M1", namespace = "FBP_Schema")
    protected RSI.M1 m1;
    @XmlElement(name = "M3", namespace = "FBP_Schema")
    protected RSI.M3 m3;
    @XmlElement(name = "M4", namespace = "FBP_Schema")
    protected RSI.M4 m4;
    @XmlElement(name = "O1", namespace = "FBP_Schema")
    protected RSI.O1 o1;
    @XmlElement(name = "Constant", namespace = "FBP_Schema")
    protected RSI.Constant constant;

    /**
     * Gets the value of the c1 property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.C1 }
     *     
     */
    public RSI.C1 getC1() {
        return c1;
    }

    /**
     * Sets the value of the c1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.C1 }
     *     
     */
    public void setC1(RSI.C1 value) {
        this.c1 = value;
    }

    /**
     * Gets the value of the c6 property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.C6 }
     *     
     */
    public RSI.C6 getC6() {
        return c6;
    }

    /**
     * Sets the value of the c6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.C6 }
     *     
     */
    public void setC6(RSI.C6 value) {
        this.c6 = value;
    }

    /**
     * Gets the value of the d2 property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.D2 }
     *     
     */
    public RSI.D2 getD2() {
        return d2;
    }

    /**
     * Sets the value of the d2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.D2 }
     *     
     */
    public void setD2(RSI.D2 value) {
        this.d2 = value;
    }

    /**
     * Gets the value of the m1 property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.M1 }
     *     
     */
    public RSI.M1 getM1() {
        return m1;
    }

    /**
     * Sets the value of the m1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.M1 }
     *     
     */
    public void setM1(RSI.M1 value) {
        this.m1 = value;
    }

    /**
     * Gets the value of the m3 property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.M3 }
     *     
     */
    public RSI.M3 getM3() {
        return m3;
    }

    /**
     * Sets the value of the m3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.M3 }
     *     
     */
    public void setM3(RSI.M3 value) {
        this.m3 = value;
    }

    /**
     * Gets the value of the m4 property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.M4 }
     *     
     */
    public RSI.M4 getM4() {
        return m4;
    }

    /**
     * Sets the value of the m4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.M4 }
     *     
     */
    public void setM4(RSI.M4 value) {
        this.m4 = value;
    }

    /**
     * Gets the value of the o1 property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.O1 }
     *     
     */
    public RSI.O1 getO1() {
        return o1;
    }

    /**
     * Sets the value of the o1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.O1 }
     *     
     */
    public void setO1(RSI.O1 value) {
        this.o1 = value;
    }

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link RSI.Constant }
     *     
     */
    public RSI.Constant getConstant() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSI.Constant }
     *     
     */
    public void setConstant(RSI.Constant value) {
        this.constant = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="C1"/&gt;
     *               &lt;enumeration value="NonFuel"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default"
    })
    public static class C1 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="C6"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Eq61_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq61_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq61_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq61_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq61_P5" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq61_P6" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq64_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq64_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq64_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class C6 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected RSI.C6 .Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link RSI.C6 .Custom }
         *     
         */
        public RSI.C6 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link RSI.C6 .Custom }
         *     
         */
        public void setCustom(RSI.C6 .Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Eq61_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq61_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq61_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq61_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq61_P5" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq61_P6" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq64_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq64_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq64_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Eq61_P1", required = true)
            protected String eq61P1;
            @XmlAttribute(name = "Eq61_P2", required = true)
            protected String eq61P2;
            @XmlAttribute(name = "Eq61_P3", required = true)
            protected String eq61P3;
            @XmlAttribute(name = "Eq61_P4", required = true)
            protected String eq61P4;
            @XmlAttribute(name = "Eq61_P5", required = true)
            protected String eq61P5;
            @XmlAttribute(name = "Eq61_P6", required = true)
            protected String eq61P6;
            @XmlAttribute(name = "Eq64_P1", required = true)
            protected String eq64P1;
            @XmlAttribute(name = "Eq64_P2", required = true)
            protected String eq64P2;
            @XmlAttribute(name = "Eq64_P3", required = true)
            protected String eq64P3;

            /**
             * Gets the value of the eq61P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq61P1() {
                return eq61P1;
            }

            /**
             * Sets the value of the eq61P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq61P1(String value) {
                this.eq61P1 = value;
            }

            /**
             * Gets the value of the eq61P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq61P2() {
                return eq61P2;
            }

            /**
             * Sets the value of the eq61P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq61P2(String value) {
                this.eq61P2 = value;
            }

            /**
             * Gets the value of the eq61P3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq61P3() {
                return eq61P3;
            }

            /**
             * Sets the value of the eq61P3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq61P3(String value) {
                this.eq61P3 = value;
            }

            /**
             * Gets the value of the eq61P4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq61P4() {
                return eq61P4;
            }

            /**
             * Sets the value of the eq61P4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq61P4(String value) {
                this.eq61P4 = value;
            }

            /**
             * Gets the value of the eq61P5 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq61P5() {
                return eq61P5;
            }

            /**
             * Sets the value of the eq61P5 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq61P5(String value) {
                this.eq61P5 = value;
            }

            /**
             * Gets the value of the eq61P6 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq61P6() {
                return eq61P6;
            }

            /**
             * Sets the value of the eq61P6 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq61P6(String value) {
                this.eq61P6 = value;
            }

            /**
             * Gets the value of the eq64P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq64P1() {
                return eq64P1;
            }

            /**
             * Sets the value of the eq64P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq64P1(String value) {
                this.eq64P1 = value;
            }

            /**
             * Gets the value of the eq64P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq64P2() {
                return eq64P2;
            }

            /**
             * Sets the value of the eq64P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq64P2(String value) {
                this.eq64P2 = value;
            }

            /**
             * Gets the value of the eq64P3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq64P3() {
                return eq64P3;
            }

            /**
             * Sets the value of the eq64P3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq64P3(String value) {
                this.eq64P3 = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="RSI" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="NZ70"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom",
        "_default"
    })
    public static class Constant {

        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected RSI.Constant.Custom custom;
        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link RSI.Constant.Custom }
         *     
         */
        public RSI.Constant.Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link RSI.Constant.Custom }
         *     
         */
        public void setCustom(RSI.Constant.Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="RSI" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "RSI", required = true)
            protected String rsi;

            /**
             * Gets the value of the rsi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRSI() {
                return rsi;
            }

            /**
             * Sets the value of the rsi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRSI(String value) {
                this.rsi = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="D2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="BUI_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Scale1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Scale2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class D2 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected RSI.D2 .Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link RSI.D2 .Custom }
         *     
         */
        public RSI.D2 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link RSI.D2 .Custom }
         *     
         */
        public void setCustom(RSI.D2 .Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="BUI_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Scale1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Scale2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "BUI_Threshold", required = true)
            protected String buiThreshold;
            @XmlAttribute(name = "Scale1", required = true)
            protected String scale1;
            @XmlAttribute(name = "Scale2", required = true)
            protected String scale2;

            /**
             * Gets the value of the buiThreshold property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBUIThreshold() {
                return buiThreshold;
            }

            /**
             * Sets the value of the buiThreshold property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBUIThreshold(String value) {
                this.buiThreshold = value;
            }

            /**
             * Gets the value of the scale1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScale1() {
                return scale1;
            }

            /**
             * Sets the value of the scale1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScale1(String value) {
                this.scale1 = value;
            }

            /**
             * Gets the value of the scale2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScale2() {
                return scale2;
            }

            /**
             * Sets the value of the scale2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScale2(String value) {
                this.scale2 = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="M1"/&gt;
     *               &lt;enumeration value="M2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class M1 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected RSI.M1 .Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link RSI.M1 .Custom }
         *     
         */
        public RSI.M1 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link RSI.M1 .Custom }
         *     
         */
        public void setCustom(RSI.M1 .Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Percentage", required = true)
            protected String percentage;

            /**
             * Gets the value of the percentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPercentage() {
                return percentage;
            }

            /**
             * Sets the value of the percentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPercentage(String value) {
                this.percentage = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="M3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M3_C2_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M3_C2_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M3_C2_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class M3 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected RSI.M3 .Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link RSI.M3 .Custom }
         *     
         */
        public RSI.M3 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link RSI.M3 .Custom }
         *     
         */
        public void setCustom(RSI.M3 .Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M3_C2_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M3_C2_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M3_C2_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Percentage", required = true)
            protected String percentage;
            @XmlAttribute(name = "M3_C2_A", required = true)
            protected String m3C2A;
            @XmlAttribute(name = "M3_C2_B", required = true)
            protected String m3C2B;
            @XmlAttribute(name = "M3_C2_C", required = true)
            protected String m3C2C;

            /**
             * Gets the value of the percentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPercentage() {
                return percentage;
            }

            /**
             * Sets the value of the percentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPercentage(String value) {
                this.percentage = value;
            }

            /**
             * Gets the value of the m3C2A property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM3C2A() {
                return m3C2A;
            }

            /**
             * Sets the value of the m3C2A property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM3C2A(String value) {
                this.m3C2A = value;
            }

            /**
             * Gets the value of the m3C2B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM3C2B() {
                return m3C2B;
            }

            /**
             * Sets the value of the m3C2B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM3C2B(String value) {
                this.m3C2B = value;
            }

            /**
             * Gets the value of the m3C2C property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM3C2C() {
                return m3C2C;
            }

            /**
             * Sets the value of the m3C2C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM3C2C(String value) {
                this.m3C2C = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="M4"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M3_C2_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M3_C2_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M3_C2_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M4_D1_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M4_D1_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="M4_D1_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class M4 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected RSI.M4 .Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link RSI.M4 .Custom }
         *     
         */
        public RSI.M4 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link RSI.M4 .Custom }
         *     
         */
        public void setCustom(RSI.M4 .Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Percentage" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M3_C2_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M3_C2_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M3_C2_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M4_D1_A" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M4_D1_B" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="M4_D1_C" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Percentage", required = true)
            protected String percentage;
            @XmlAttribute(name = "M3_C2_A", required = true)
            protected String m3C2A;
            @XmlAttribute(name = "M3_C2_B", required = true)
            protected String m3C2B;
            @XmlAttribute(name = "M3_C2_C", required = true)
            protected String m3C2C;
            @XmlAttribute(name = "M4_D1_A", required = true)
            protected String m4D1A;
            @XmlAttribute(name = "M4_D1_B", required = true)
            protected String m4D1B;
            @XmlAttribute(name = "M4_D1_C", required = true)
            protected String m4D1C;

            /**
             * Gets the value of the percentage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPercentage() {
                return percentage;
            }

            /**
             * Sets the value of the percentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPercentage(String value) {
                this.percentage = value;
            }

            /**
             * Gets the value of the m3C2A property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM3C2A() {
                return m3C2A;
            }

            /**
             * Sets the value of the m3C2A property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM3C2A(String value) {
                this.m3C2A = value;
            }

            /**
             * Gets the value of the m3C2B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM3C2B() {
                return m3C2B;
            }

            /**
             * Sets the value of the m3C2B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM3C2B(String value) {
                this.m3C2B = value;
            }

            /**
             * Gets the value of the m3C2C property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM3C2C() {
                return m3C2C;
            }

            /**
             * Sets the value of the m3C2C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM3C2C(String value) {
                this.m3C2C = value;
            }

            /**
             * Gets the value of the m4D1A property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM4D1A() {
                return m4D1A;
            }

            /**
             * Sets the value of the m4D1A property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM4D1A(String value) {
                this.m4D1A = value;
            }

            /**
             * Gets the value of the m4D1B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM4D1B() {
                return m4D1B;
            }

            /**
             * Sets the value of the m4D1B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM4D1B(String value) {
                this.m4D1B = value;
            }

            /**
             * Gets the value of the m4D1C property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getM4D1C() {
                return m4D1C;
            }

            /**
             * Sets the value of the m4D1C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setM4D1C(String value) {
                this.m4D1C = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="O1a"/&gt;
     *               &lt;enumeration value="O1b"/&gt;
     *               &lt;enumeration value="O1ab"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="C_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq35a_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq35a_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq35b_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq35b_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default",
        "custom"
    })
    public static class O1 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;
        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected RSI.O1 .Custom custom;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link RSI.O1 .Custom }
         *     
         */
        public RSI.O1 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link RSI.O1 .Custom }
         *     
         */
        public void setCustom(RSI.O1 .Custom value) {
            this.custom = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="C_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq35a_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq35a_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq35b_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq35b_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "C_Threshold", required = true)
            protected String cThreshold;
            @XmlAttribute(name = "Eq35a_P1", required = true)
            protected String eq35AP1;
            @XmlAttribute(name = "Eq35a_P2", required = true)
            protected String eq35AP2;
            @XmlAttribute(name = "Eq35b_P1", required = true)
            protected String eq35BP1;
            @XmlAttribute(name = "Eq35b_P2", required = true)
            protected String eq35BP2;

            /**
             * Gets the value of the cThreshold property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCThreshold() {
                return cThreshold;
            }

            /**
             * Sets the value of the cThreshold property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCThreshold(String value) {
                this.cThreshold = value;
            }

            /**
             * Gets the value of the eq35AP1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq35AP1() {
                return eq35AP1;
            }

            /**
             * Sets the value of the eq35AP1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq35AP1(String value) {
                this.eq35AP1 = value;
            }

            /**
             * Gets the value of the eq35AP2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq35AP2() {
                return eq35AP2;
            }

            /**
             * Sets the value of the eq35AP2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq35AP2(String value) {
                this.eq35AP2 = value;
            }

            /**
             * Gets the value of the eq35BP1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq35BP1() {
                return eq35BP1;
            }

            /**
             * Sets the value of the eq35BP1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq35BP1(String value) {
                this.eq35BP1 = value;
            }

            /**
             * Gets the value of the eq35BP2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq35BP2() {
                return eq35BP2;
            }

            /**
             * Sets the value of the eq35BP2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq35BP2(String value) {
                this.eq35BP2 = value;
            }

        }

    }

}
