//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.03.23 at 01:37:57 PM CDT 
//


package ca.wise.fgm.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SFC complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SFC"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="C1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Eq9_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq9_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq9_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq9_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="C1"/&gt;
 *                         &lt;enumeration value="NonFuel"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="C2"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Eq10_Multiplier" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq10_Adder" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq10_Power" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="C2"/&gt;
 *                         &lt;enumeration value="M3"/&gt;
 *                         &lt;enumeration value="M4"/&gt;
 *                         &lt;enumeration value="C3"/&gt;
 *                         &lt;enumeration value="C4"/&gt;
 *                         &lt;enumeration value="C5"/&gt;
 *                         &lt;enumeration value="C6"/&gt;
 *                         &lt;enumeration value="D1"/&gt;
 *                         &lt;enumeration value="NZ54"/&gt;
 *                         &lt;enumeration value="NZ60"/&gt;
 *                         &lt;enumeration value="NZ61"/&gt;
 *                         &lt;enumeration value="NZ67"/&gt;
 *                         &lt;enumeration value="NZ68"/&gt;
 *                         &lt;enumeration value="NZ69"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="C7"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Eq13_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq13_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq13_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq14_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq14_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="FFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="WFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="C7"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="D2"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Eq10_Multiplier" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq10_Adder" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq10_Power" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="D2_Multiplier1" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="D2_Multiplier2" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="D2_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="D2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="M1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="M1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="O1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="GFL" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="A_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="B_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="C_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="A_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="B_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="C_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="O1a"/&gt;
 *                         &lt;enumeration value="O1b"/&gt;
 *                         &lt;enumeration value="NZ2"/&gt;
 *                         &lt;enumeration value="NZ15"/&gt;
 *                         &lt;enumeration value="NZ30"/&gt;
 *                         &lt;enumeration value="NZ31"/&gt;
 *                         &lt;enumeration value="NZ32"/&gt;
 *                         &lt;enumeration value="NZ33"/&gt;
 *                         &lt;enumeration value="NZ40"/&gt;
 *                         &lt;enumeration value="NZ41"/&gt;
 *                         &lt;enumeration value="NZ43"/&gt;
 *                         &lt;enumeration value="NZ44"/&gt;
 *                         &lt;enumeration value="NZ45"/&gt;
 *                         &lt;enumeration value="NZ46"/&gt;
 *                         &lt;enumeration value="NZ47"/&gt;
 *                         &lt;enumeration value="NZ50"/&gt;
 *                         &lt;enumeration value="NZ51"/&gt;
 *                         &lt;enumeration value="NZ52"/&gt;
 *                         &lt;enumeration value="NZ53"/&gt;
 *                         &lt;enumeration value="NZ55"/&gt;
 *                         &lt;enumeration value="NZ56"/&gt;
 *                         &lt;enumeration value="NZ57"/&gt;
 *                         &lt;enumeration value="NZ58"/&gt;
 *                         &lt;enumeration value="NZ62"/&gt;
 *                         &lt;enumeration value="NZ70"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="S1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="Custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="WFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="FFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="FFC_BUI_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="WFC_BUI_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq19_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq19_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq20_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                           &lt;attribute name="Eq20_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Default"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="S1"/&gt;
 *                         &lt;enumeration value="S2"/&gt;
 *                         &lt;enumeration value="S3"/&gt;
 *                         &lt;enumeration value="NZ63"/&gt;
 *                         &lt;enumeration value="NZ64"/&gt;
 *                         &lt;enumeration value="NZ65"/&gt;
 *                         &lt;enumeration value="NZ66"/&gt;
 *                         &lt;enumeration value="NZ71"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SFC", namespace = "FBP_Schema", propOrder = {
    "c1",
    "c2",
    "c7",
    "d2",
    "m1",
    "o1",
    "s1"
})
public class SFC {

    @XmlElement(name = "C1", namespace = "FBP_Schema")
    protected SFC.C1 c1;
    @XmlElement(name = "C2", namespace = "FBP_Schema")
    protected SFC.C2 c2;
    @XmlElement(name = "C7", namespace = "FBP_Schema")
    protected SFC.C7 c7;
    @XmlElement(name = "D2", namespace = "FBP_Schema")
    protected SFC.D2 d2;
    @XmlElement(name = "M1", namespace = "FBP_Schema")
    protected SFC.M1 m1;
    @XmlElement(name = "O1", namespace = "FBP_Schema")
    protected SFC.O1 o1;
    @XmlElement(name = "S1", namespace = "FBP_Schema")
    protected SFC.S1 s1;

    /**
     * Gets the value of the c1 property.
     * 
     * @return
     *     possible object is
     *     {@link SFC.C1 }
     *     
     */
    public SFC.C1 getC1() {
        return c1;
    }

    /**
     * Sets the value of the c1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFC.C1 }
     *     
     */
    public void setC1(SFC.C1 value) {
        this.c1 = value;
    }

    /**
     * Gets the value of the c2 property.
     * 
     * @return
     *     possible object is
     *     {@link SFC.C2 }
     *     
     */
    public SFC.C2 getC2() {
        return c2;
    }

    /**
     * Sets the value of the c2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFC.C2 }
     *     
     */
    public void setC2(SFC.C2 value) {
        this.c2 = value;
    }

    /**
     * Gets the value of the c7 property.
     * 
     * @return
     *     possible object is
     *     {@link SFC.C7 }
     *     
     */
    public SFC.C7 getC7() {
        return c7;
    }

    /**
     * Sets the value of the c7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFC.C7 }
     *     
     */
    public void setC7(SFC.C7 value) {
        this.c7 = value;
    }

    /**
     * Gets the value of the d2 property.
     * 
     * @return
     *     possible object is
     *     {@link SFC.D2 }
     *     
     */
    public SFC.D2 getD2() {
        return d2;
    }

    /**
     * Sets the value of the d2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFC.D2 }
     *     
     */
    public void setD2(SFC.D2 value) {
        this.d2 = value;
    }

    /**
     * Gets the value of the m1 property.
     * 
     * @return
     *     possible object is
     *     {@link SFC.M1 }
     *     
     */
    public SFC.M1 getM1() {
        return m1;
    }

    /**
     * Sets the value of the m1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFC.M1 }
     *     
     */
    public void setM1(SFC.M1 value) {
        this.m1 = value;
    }

    /**
     * Gets the value of the o1 property.
     * 
     * @return
     *     possible object is
     *     {@link SFC.O1 }
     *     
     */
    public SFC.O1 getO1() {
        return o1;
    }

    /**
     * Sets the value of the o1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFC.O1 }
     *     
     */
    public void setO1(SFC.O1 value) {
        this.o1 = value;
    }

    /**
     * Gets the value of the s1 property.
     * 
     * @return
     *     possible object is
     *     {@link SFC.S1 }
     *     
     */
    public SFC.S1 getS1() {
        return s1;
    }

    /**
     * Sets the value of the s1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFC.S1 }
     *     
     */
    public void setS1(SFC.S1 value) {
        this.s1 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Eq9_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq9_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq9_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq9_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="C1"/&gt;
     *               &lt;enumeration value="NonFuel"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom",
        "_default"
    })
    public static class C1 {

        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected SFC.C1 .Custom custom;
        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link SFC.C1 .Custom }
         *     
         */
        public SFC.C1 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link SFC.C1 .Custom }
         *     
         */
        public void setCustom(SFC.C1 .Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Eq9_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq9_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq9_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq9_P4" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Eq9_P1", required = true)
            protected String eq9P1;
            @XmlAttribute(name = "Eq9_P2", required = true)
            protected String eq9P2;
            @XmlAttribute(name = "Eq9_P3", required = true)
            protected String eq9P3;
            @XmlAttribute(name = "Eq9_P4", required = true)
            protected String eq9P4;
            @XmlAttribute(name = "SFC_Multiplier")
            protected String sfcMultiplier;

            /**
             * Gets the value of the eq9P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq9P1() {
                return eq9P1;
            }

            /**
             * Sets the value of the eq9P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq9P1(String value) {
                this.eq9P1 = value;
            }

            /**
             * Gets the value of the eq9P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq9P2() {
                return eq9P2;
            }

            /**
             * Sets the value of the eq9P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq9P2(String value) {
                this.eq9P2 = value;
            }

            /**
             * Gets the value of the eq9P3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq9P3() {
                return eq9P3;
            }

            /**
             * Sets the value of the eq9P3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq9P3(String value) {
                this.eq9P3 = value;
            }

            /**
             * Gets the value of the eq9P4 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq9P4() {
                return eq9P4;
            }

            /**
             * Sets the value of the eq9P4 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq9P4(String value) {
                this.eq9P4 = value;
            }

            /**
             * Gets the value of the sfcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSFCMultiplier() {
                return sfcMultiplier;
            }

            /**
             * Sets the value of the sfcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSFCMultiplier(String value) {
                this.sfcMultiplier = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Eq10_Multiplier" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq10_Adder" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq10_Power" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="C2"/&gt;
     *               &lt;enumeration value="M3"/&gt;
     *               &lt;enumeration value="M4"/&gt;
     *               &lt;enumeration value="C3"/&gt;
     *               &lt;enumeration value="C4"/&gt;
     *               &lt;enumeration value="C5"/&gt;
     *               &lt;enumeration value="C6"/&gt;
     *               &lt;enumeration value="D1"/&gt;
     *               &lt;enumeration value="NZ54"/&gt;
     *               &lt;enumeration value="NZ60"/&gt;
     *               &lt;enumeration value="NZ61"/&gt;
     *               &lt;enumeration value="NZ67"/&gt;
     *               &lt;enumeration value="NZ68"/&gt;
     *               &lt;enumeration value="NZ69"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom",
        "_default"
    })
    public static class C2 {

        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected SFC.C2 .Custom custom;
        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link SFC.C2 .Custom }
         *     
         */
        public SFC.C2 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link SFC.C2 .Custom }
         *     
         */
        public void setCustom(SFC.C2 .Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Eq10_Multiplier" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq10_Adder" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq10_Power" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Eq10_Multiplier", required = true)
            protected String eq10Multiplier;
            @XmlAttribute(name = "Eq10_Adder", required = true)
            protected String eq10Adder;
            @XmlAttribute(name = "Eq10_Power", required = true)
            protected String eq10Power;
            @XmlAttribute(name = "SFC_Multiplier")
            protected String sfcMultiplier;

            /**
             * Gets the value of the eq10Multiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq10Multiplier() {
                return eq10Multiplier;
            }

            /**
             * Sets the value of the eq10Multiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq10Multiplier(String value) {
                this.eq10Multiplier = value;
            }

            /**
             * Gets the value of the eq10Adder property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq10Adder() {
                return eq10Adder;
            }

            /**
             * Sets the value of the eq10Adder property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq10Adder(String value) {
                this.eq10Adder = value;
            }

            /**
             * Gets the value of the eq10Power property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq10Power() {
                return eq10Power;
            }

            /**
             * Sets the value of the eq10Power property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq10Power(String value) {
                this.eq10Power = value;
            }

            /**
             * Gets the value of the sfcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSFCMultiplier() {
                return sfcMultiplier;
            }

            /**
             * Sets the value of the sfcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSFCMultiplier(String value) {
                this.sfcMultiplier = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Eq13_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq13_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq13_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq14_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq14_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="FFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="WFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="C7"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom",
        "_default"
    })
    public static class C7 {

        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected SFC.C7 .Custom custom;
        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link SFC.C7 .Custom }
         *     
         */
        public SFC.C7 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link SFC.C7 .Custom }
         *     
         */
        public void setCustom(SFC.C7 .Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Eq13_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq13_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq13_P3" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq14_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq14_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="FFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="WFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Eq13_P1", required = true)
            protected String eq13P1;
            @XmlAttribute(name = "Eq13_P2", required = true)
            protected String eq13P2;
            @XmlAttribute(name = "Eq13_P3", required = true)
            protected String eq13P3;
            @XmlAttribute(name = "Eq14_P1", required = true)
            protected String eq14P1;
            @XmlAttribute(name = "Eq14_P2", required = true)
            protected String eq14P2;
            @XmlAttribute(name = "FFC_Multiplier")
            protected String ffcMultiplier;
            @XmlAttribute(name = "WFC_Multiplier")
            protected String wfcMultiplier;
            @XmlAttribute(name = "SFC_Multiplier")
            protected String sfcMultiplier;

            /**
             * Gets the value of the eq13P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq13P1() {
                return eq13P1;
            }

            /**
             * Sets the value of the eq13P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq13P1(String value) {
                this.eq13P1 = value;
            }

            /**
             * Gets the value of the eq13P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq13P2() {
                return eq13P2;
            }

            /**
             * Sets the value of the eq13P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq13P2(String value) {
                this.eq13P2 = value;
            }

            /**
             * Gets the value of the eq13P3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq13P3() {
                return eq13P3;
            }

            /**
             * Sets the value of the eq13P3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq13P3(String value) {
                this.eq13P3 = value;
            }

            /**
             * Gets the value of the eq14P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq14P1() {
                return eq14P1;
            }

            /**
             * Sets the value of the eq14P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq14P1(String value) {
                this.eq14P1 = value;
            }

            /**
             * Gets the value of the eq14P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq14P2() {
                return eq14P2;
            }

            /**
             * Sets the value of the eq14P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq14P2(String value) {
                this.eq14P2 = value;
            }

            /**
             * Gets the value of the ffcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFFCMultiplier() {
                return ffcMultiplier;
            }

            /**
             * Sets the value of the ffcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFFCMultiplier(String value) {
                this.ffcMultiplier = value;
            }

            /**
             * Gets the value of the wfcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWFCMultiplier() {
                return wfcMultiplier;
            }

            /**
             * Sets the value of the wfcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWFCMultiplier(String value) {
                this.wfcMultiplier = value;
            }

            /**
             * Gets the value of the sfcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSFCMultiplier() {
                return sfcMultiplier;
            }

            /**
             * Sets the value of the sfcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSFCMultiplier(String value) {
                this.sfcMultiplier = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Eq10_Multiplier" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq10_Adder" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq10_Power" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="D2_Multiplier1" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="D2_Multiplier2" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="D2_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="D2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom",
        "_default"
    })
    public static class D2 {

        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected SFC.D2 .Custom custom;
        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link SFC.D2 .Custom }
         *     
         */
        public SFC.D2 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link SFC.D2 .Custom }
         *     
         */
        public void setCustom(SFC.D2 .Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Eq10_Multiplier" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq10_Adder" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq10_Power" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="D2_Multiplier1" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="D2_Multiplier2" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="D2_Threshold" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "Eq10_Multiplier", required = true)
            protected String eq10Multiplier;
            @XmlAttribute(name = "Eq10_Adder", required = true)
            protected String eq10Adder;
            @XmlAttribute(name = "Eq10_Power", required = true)
            protected String eq10Power;
            @XmlAttribute(name = "SFC_Multiplier")
            protected String sfcMultiplier;
            @XmlAttribute(name = "D2_Multiplier1")
            protected String d2Multiplier1;
            @XmlAttribute(name = "D2_Multiplier2")
            protected String d2Multiplier2;
            @XmlAttribute(name = "D2_Threshold", required = true)
            protected String d2Threshold;

            /**
             * Gets the value of the eq10Multiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq10Multiplier() {
                return eq10Multiplier;
            }

            /**
             * Sets the value of the eq10Multiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq10Multiplier(String value) {
                this.eq10Multiplier = value;
            }

            /**
             * Gets the value of the eq10Adder property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq10Adder() {
                return eq10Adder;
            }

            /**
             * Sets the value of the eq10Adder property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq10Adder(String value) {
                this.eq10Adder = value;
            }

            /**
             * Gets the value of the eq10Power property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq10Power() {
                return eq10Power;
            }

            /**
             * Sets the value of the eq10Power property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq10Power(String value) {
                this.eq10Power = value;
            }

            /**
             * Gets the value of the sfcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSFCMultiplier() {
                return sfcMultiplier;
            }

            /**
             * Sets the value of the sfcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSFCMultiplier(String value) {
                this.sfcMultiplier = value;
            }

            /**
             * Gets the value of the d2Multiplier1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getD2Multiplier1() {
                return d2Multiplier1;
            }

            /**
             * Sets the value of the d2Multiplier1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setD2Multiplier1(String value) {
                this.d2Multiplier1 = value;
            }

            /**
             * Gets the value of the d2Multiplier2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getD2Multiplier2() {
                return d2Multiplier2;
            }

            /**
             * Sets the value of the d2Multiplier2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setD2Multiplier2(String value) {
                this.d2Multiplier2 = value;
            }

            /**
             * Gets the value of the d2Threshold property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getD2Threshold() {
                return d2Threshold;
            }

            /**
             * Sets the value of the d2Threshold property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setD2Threshold(String value) {
                this.d2Threshold = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="M1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "_default"
    })
    public static class M1 {

        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="GFL" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="A_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="B_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="C_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="A_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="B_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="C_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="O1a"/&gt;
     *               &lt;enumeration value="O1b"/&gt;
     *               &lt;enumeration value="NZ2"/&gt;
     *               &lt;enumeration value="NZ15"/&gt;
     *               &lt;enumeration value="NZ30"/&gt;
     *               &lt;enumeration value="NZ31"/&gt;
     *               &lt;enumeration value="NZ32"/&gt;
     *               &lt;enumeration value="NZ33"/&gt;
     *               &lt;enumeration value="NZ40"/&gt;
     *               &lt;enumeration value="NZ41"/&gt;
     *               &lt;enumeration value="NZ43"/&gt;
     *               &lt;enumeration value="NZ44"/&gt;
     *               &lt;enumeration value="NZ45"/&gt;
     *               &lt;enumeration value="NZ46"/&gt;
     *               &lt;enumeration value="NZ47"/&gt;
     *               &lt;enumeration value="NZ50"/&gt;
     *               &lt;enumeration value="NZ51"/&gt;
     *               &lt;enumeration value="NZ52"/&gt;
     *               &lt;enumeration value="NZ53"/&gt;
     *               &lt;enumeration value="NZ55"/&gt;
     *               &lt;enumeration value="NZ56"/&gt;
     *               &lt;enumeration value="NZ57"/&gt;
     *               &lt;enumeration value="NZ58"/&gt;
     *               &lt;enumeration value="NZ62"/&gt;
     *               &lt;enumeration value="NZ70"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom",
        "_default"
    })
    public static class O1 {

        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected SFC.O1 .Custom custom;
        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link SFC.O1 .Custom }
         *     
         */
        public SFC.O1 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link SFC.O1 .Custom }
         *     
         */
        public void setCustom(SFC.O1 .Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="GFL" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="A_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="B_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="C_matted" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="A_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="B_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="C_standing" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "GFL", required = true)
            protected String gfl;
            @XmlAttribute(name = "A_matted", required = true)
            protected String aMatted;
            @XmlAttribute(name = "B_matted", required = true)
            protected String bMatted;
            @XmlAttribute(name = "C_matted", required = true)
            protected String cMatted;
            @XmlAttribute(name = "A_standing", required = true)
            protected String aStanding;
            @XmlAttribute(name = "B_standing", required = true)
            protected String bStanding;
            @XmlAttribute(name = "C_standing", required = true)
            protected String cStanding;

            /**
             * Gets the value of the gfl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGFL() {
                return gfl;
            }

            /**
             * Sets the value of the gfl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGFL(String value) {
                this.gfl = value;
            }

            /**
             * Gets the value of the aMatted property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAMatted() {
                return aMatted;
            }

            /**
             * Sets the value of the aMatted property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAMatted(String value) {
                this.aMatted = value;
            }

            /**
             * Gets the value of the bMatted property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBMatted() {
                return bMatted;
            }

            /**
             * Sets the value of the bMatted property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBMatted(String value) {
                this.bMatted = value;
            }

            /**
             * Gets the value of the cMatted property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCMatted() {
                return cMatted;
            }

            /**
             * Sets the value of the cMatted property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCMatted(String value) {
                this.cMatted = value;
            }

            /**
             * Gets the value of the aStanding property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAStanding() {
                return aStanding;
            }

            /**
             * Sets the value of the aStanding property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAStanding(String value) {
                this.aStanding = value;
            }

            /**
             * Gets the value of the bStanding property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBStanding() {
                return bStanding;
            }

            /**
             * Sets the value of the bStanding property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBStanding(String value) {
                this.bStanding = value;
            }

            /**
             * Gets the value of the cStanding property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCStanding() {
                return cStanding;
            }

            /**
             * Sets the value of the cStanding property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCStanding(String value) {
                this.cStanding = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="Custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="WFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="FFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="FFC_BUI_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="WFC_BUI_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq19_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq19_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq20_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *                 &lt;attribute name="Eq20_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Default"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="S1"/&gt;
     *               &lt;enumeration value="S2"/&gt;
     *               &lt;enumeration value="S3"/&gt;
     *               &lt;enumeration value="NZ63"/&gt;
     *               &lt;enumeration value="NZ64"/&gt;
     *               &lt;enumeration value="NZ65"/&gt;
     *               &lt;enumeration value="NZ66"/&gt;
     *               &lt;enumeration value="NZ71"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom",
        "_default"
    })
    public static class S1 {

        @XmlElement(name = "Custom", namespace = "FBP_Schema")
        protected SFC.S1 .Custom custom;
        @XmlElement(name = "Default", namespace = "FBP_Schema")
        protected String _default;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link SFC.S1 .Custom }
         *     
         */
        public SFC.S1 .Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link SFC.S1 .Custom }
         *     
         */
        public void setCustom(SFC.S1 .Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the default property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefault() {
            return _default;
        }

        /**
         * Sets the value of the default property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefault(String value) {
            this._default = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="SFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="WFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="FFC_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="FFC_BUI_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="WFC_BUI_Multiplier" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq19_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq19_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq20_P1" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *       &lt;attribute name="Eq20_P2" use="required" type="{http://www.heartlandsoftware.ca/xml/types}Double" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Custom {

            @XmlAttribute(name = "SFC_Multiplier")
            protected String sfcMultiplier;
            @XmlAttribute(name = "WFC_Multiplier")
            protected String wfcMultiplier;
            @XmlAttribute(name = "FFC_Multiplier")
            protected String ffcMultiplier;
            @XmlAttribute(name = "FFC_BUI_Multiplier")
            protected String ffcbuiMultiplier;
            @XmlAttribute(name = "WFC_BUI_Multiplier")
            protected String wfcbuiMultiplier;
            @XmlAttribute(name = "Eq19_P1", required = true)
            protected String eq19P1;
            @XmlAttribute(name = "Eq19_P2", required = true)
            protected String eq19P2;
            @XmlAttribute(name = "Eq20_P1", required = true)
            protected String eq20P1;
            @XmlAttribute(name = "Eq20_P2", required = true)
            protected String eq20P2;

            /**
             * Gets the value of the sfcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSFCMultiplier() {
                return sfcMultiplier;
            }

            /**
             * Sets the value of the sfcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSFCMultiplier(String value) {
                this.sfcMultiplier = value;
            }

            /**
             * Gets the value of the wfcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWFCMultiplier() {
                return wfcMultiplier;
            }

            /**
             * Sets the value of the wfcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWFCMultiplier(String value) {
                this.wfcMultiplier = value;
            }

            /**
             * Gets the value of the ffcMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFFCMultiplier() {
                return ffcMultiplier;
            }

            /**
             * Sets the value of the ffcMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFFCMultiplier(String value) {
                this.ffcMultiplier = value;
            }

            /**
             * Gets the value of the ffcbuiMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFFCBUIMultiplier() {
                return ffcbuiMultiplier;
            }

            /**
             * Sets the value of the ffcbuiMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFFCBUIMultiplier(String value) {
                this.ffcbuiMultiplier = value;
            }

            /**
             * Gets the value of the wfcbuiMultiplier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWFCBUIMultiplier() {
                return wfcbuiMultiplier;
            }

            /**
             * Sets the value of the wfcbuiMultiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWFCBUIMultiplier(String value) {
                this.wfcbuiMultiplier = value;
            }

            /**
             * Gets the value of the eq19P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq19P1() {
                return eq19P1;
            }

            /**
             * Sets the value of the eq19P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq19P1(String value) {
                this.eq19P1 = value;
            }

            /**
             * Gets the value of the eq19P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq19P2() {
                return eq19P2;
            }

            /**
             * Sets the value of the eq19P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq19P2(String value) {
                this.eq19P2 = value;
            }

            /**
             * Gets the value of the eq20P1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq20P1() {
                return eq20P1;
            }

            /**
             * Sets the value of the eq20P1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq20P1(String value) {
                this.eq20P1 = value;
            }

            /**
             * Gets the value of the eq20P2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEq20P2() {
                return eq20P2;
            }

            /**
             * Sets the value of the eq20P2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEq20P2(String value) {
                this.eq20P2 = value;
            }

        }

    }

}
