//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.01.10 at 10:49:01 AM CST 
//


package ca.wise.fgm.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wfsData complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wfsData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="locationFile"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="projectionFile" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="gisResource" type="{http://www.heartlandsoftware.ca/xml/types}wfsType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="vectorData" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="zipResource" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="point" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="polyline" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="polygon" minOccurs="0"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="width" type="{http://www.heartlandsoftware.ca/xml/types}Double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wfsData", propOrder = {
    "locationFile",
    "gisResource",
    "vectorData",
    "width"
})
@XmlSeeAlso({
    ca.wise.fgm.xml.Data.Job.Inputs.Files.FuelPatchFiles.FuelPatchFile.Geographic.Coordinates.class,
    ca.wise.fgm.xml.Data.Job.Inputs.Files.WeatherPatchFiles.PatchFile.Geographic.Coordinates.class,
    ca.wise.fgm.xml.Data.Job.Inputs.Ignitions.Ignition.Coordinates.class
})
public class WfsData {

    @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
    protected WfsData.LocationFile locationFile;
    @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
    protected WfsType gisResource;
    @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
    protected List<WfsData.VectorData> vectorData;
    @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
    protected String width;

    /**
     * Gets the value of the locationFile property.
     * 
     * @return
     *     possible object is
     *     {@link WfsData.LocationFile }
     *     
     */
    public WfsData.LocationFile getLocationFile() {
        return locationFile;
    }

    /**
     * Sets the value of the locationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link WfsData.LocationFile }
     *     
     */
    public void setLocationFile(WfsData.LocationFile value) {
        this.locationFile = value;
    }

    /**
     * Gets the value of the gisResource property.
     * 
     * @return
     *     possible object is
     *     {@link WfsType }
     *     
     */
    public WfsType getGisResource() {
        return gisResource;
    }

    /**
     * Sets the value of the gisResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link WfsType }
     *     
     */
    public void setGisResource(WfsType value) {
        this.gisResource = value;
    }

    /**
     * Gets the value of the vectorData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vectorData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVectorData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WfsData.VectorData }
     * 
     * 
     */
    public List<WfsData.VectorData> getVectorData() {
        if (vectorData == null) {
            vectorData = new ArrayList<WfsData.VectorData>();
        }
        return this.vectorData;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="projectionFile" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LocationFile {

        @XmlAttribute(name = "fileName", required = true)
        protected String fileName;
        @XmlAttribute(name = "projectionFile")
        protected String projectionFile;

        /**
         * Gets the value of the fileName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileName() {
            return fileName;
        }

        /**
         * Sets the value of the fileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileName(String value) {
            this.fileName = value;
        }

        /**
         * Gets the value of the projectionFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProjectionFile() {
            return projectionFile;
        }

        /**
         * Sets the value of the projectionFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProjectionFile(String value) {
            this.projectionFile = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="zipResource" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="point" minOccurs="0"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *         &lt;/sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="polyline" minOccurs="0"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *         &lt;/sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="polygon" minOccurs="0"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *         &lt;/sequence&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zipResource",
        "point",
        "polyline",
        "polygon"
    })
    public static class VectorData {

        @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
        protected String zipResource;
        @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
        protected WfsData.VectorData.Point point;
        @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
        protected WfsData.VectorData.Polyline polyline;
        @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types")
        protected WfsData.VectorData.Polygon polygon;

        /**
         * Gets the value of the zipResource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZipResource() {
            return zipResource;
        }

        /**
         * Sets the value of the zipResource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZipResource(String value) {
            this.zipResource = value;
        }

        /**
         * Gets the value of the point property.
         * 
         * @return
         *     possible object is
         *     {@link WfsData.VectorData.Point }
         *     
         */
        public WfsData.VectorData.Point getPoint() {
            return point;
        }

        /**
         * Sets the value of the point property.
         * 
         * @param value
         *     allowed object is
         *     {@link WfsData.VectorData.Point }
         *     
         */
        public void setPoint(WfsData.VectorData.Point value) {
            this.point = value;
        }

        /**
         * Gets the value of the polyline property.
         * 
         * @return
         *     possible object is
         *     {@link WfsData.VectorData.Polyline }
         *     
         */
        public WfsData.VectorData.Polyline getPolyline() {
            return polyline;
        }

        /**
         * Sets the value of the polyline property.
         * 
         * @param value
         *     allowed object is
         *     {@link WfsData.VectorData.Polyline }
         *     
         */
        public void setPolyline(WfsData.VectorData.Polyline value) {
            this.polyline = value;
        }

        /**
         * Gets the value of the polygon property.
         * 
         * @return
         *     possible object is
         *     {@link WfsData.VectorData.Polygon }
         *     
         */
        public WfsData.VectorData.Polygon getPolygon() {
            return polygon;
        }

        /**
         * Sets the value of the polygon property.
         * 
         * @param value
         *     allowed object is
         *     {@link WfsData.VectorData.Polygon }
         *     
         */
        public void setPolygon(WfsData.VectorData.Polygon value) {
            this.polygon = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "location"
        })
        public static class Point {

            @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types", required = true)
            protected List<CoordinateType> location;

            /**
             * Gets the value of the location property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the location property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLocation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CoordinateType }
             * 
             * 
             */
            public List<CoordinateType> getLocation() {
                if (location == null) {
                    location = new ArrayList<CoordinateType>();
                }
                return this.location;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "location"
        })
        public static class Polygon {

            @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types", required = true)
            protected List<CoordinateType> location;

            /**
             * Gets the value of the location property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the location property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLocation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CoordinateType }
             * 
             * 
             */
            public List<CoordinateType> getLocation() {
                if (location == null) {
                    location = new ArrayList<CoordinateType>();
                }
                return this.location;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="location" type="{http://www.heartlandsoftware.ca/xml/types}coordinateType" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "location"
        })
        public static class Polyline {

            @XmlElement(namespace = "http://www.heartlandsoftware.ca/xml/types", required = true)
            protected List<CoordinateType> location;

            /**
             * Gets the value of the location property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the location property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLocation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CoordinateType }
             * 
             * 
             */
            public List<CoordinateType> getLocation() {
                if (location == null) {
                    location = new ArrayList<CoordinateType>();
                }
                return this.location;
            }

        }

    }

}
